In [738]:
import pandas as pd

In [739]:
arr = pd.read_csv("../res/tin00174_linear.csv")

In [740]:
arr

,DATAFLOW,LAST UPDATE,freq,c_resid,unit,nace_r2,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:TIN00174(1.0),28/05/26 11:00:00,Annual,Domestic country,Number,Hotels; holiday and other short-stay accommoda...,Albania,2018,476294,e,NaN
1,ESTAT:TIN00174(1.0),28/05/26 11:00:00,Annual,Domestic country,Number,Hotels; holiday and other short-stay accommoda...,Albania,2019,468787,e,NaN
2,ESTAT:TIN00174(1.0),28/05/26 11:00:00,Annual,Domestic country,Number,Hotels; holiday and other short-stay accommoda...,Albania,2020,371523,e,NaN
3,ESTAT:TIN00174(1.0),28/05/26 11:00:00,Annual,Domestic country,Number,Hotels; holiday and other short-stay accommoda...,Albania,2021,545835,e,NaN
4,ESTAT:TIN00174(1.0),28/05/26 11:00:00,Annual,Domestic country,Number,Hotels; holiday and other short-stay accommoda...,Albania,2022,683467,e,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1145,ESTAT:TIN00174(1.0),28/05/26 11:00:00,Annual,Total,Number,Hotels; holiday and other short-stay accommoda...,Türkiye,2023,77298091,NaN,NaN
1146,ESTAT:TIN00174(1.0),28/05/26 11:00:00,Annual,Total,Number,Hotels; holiday and other short-stay accommoda...,Türkiye,2024,83243556,NaN,NaN
1147,ESTAT:TIN00174(1.0),28/05/26 11:00:00,Annual,Total,Number,Hotels; holiday and other short-stay accommoda...,United Kingdom,2014,117699620,NaN,NaN
1148,ESTAT:TIN00174(1.0),28/05/26 11:00:00,Annual,Total,Number,Hotels; holiday and other short-stay accommoda...,United Kingdom,2015,124410269,NaN,NaN
1149,ESTAT:TIN00174(1.0),28/05/26 11:00:00,Annual,Total,Number,Hotels; holiday and other short-stay accommoda...,United Kingdom,2016,122041074,NaN,NaN

In [741]:
arr = arr[["geo", "TIME_PERIOD", "c_resid", "OBS_VALUE"]]
arr.columns = ["country", "year", "resid", "arrivals"]
arr.sort_values(by=['resid', 'country', 'year'], inplace=True)
arr.reset_index(drop=True, inplace=True)

In [742]:
print(arr.to_string())

                                        country  year             resid    arrivals
0                                       Albania  2018  Domestic country      476294
1                                       Albania  2019  Domestic country      468787
2                                       Albania  2020  Domestic country      371523
3                                       Albania  2021  Domestic country      545835
4                                       Albania  2022  Domestic country      683467
5                                       Albania  2023  Domestic country      926803
6                                       Albania  2024  Domestic country      993348
7                                       Austria  2014  Domestic country    11400395
8                                       Austria  2015  Domestic country    11805718
9                                       Austria  2016  Domestic country    12413155
10                                      Austria  2017  Domestic country    12680617
11                                      Austria  2018  Domestic country    13087273
12                                      Austria  2019  Domestic country    13359120
13                                      Austria  2020  Domestic country     9034335
14                                      Austria  2021  Domestic country     8659900
15                                      Austria  2022  Domestic country    12695341
16                                      Austria  2023  Domestic country    13437243
17                                      Austria  2024  Domestic country    13669736
18                                      Austria  2025  Domestic country    13816162
19                                      Belgium  2014  Domestic country     6753644
20                                      Belgium  2015  Domestic country     7492173
21                                      Belgium  2016  Domestic country     7729359
22                                      Belgium  2017  Domestic country     7934684
23                                      Belgium  2018  Domestic country     8441061
24                                      Belgium  2019  Domestic country     8714287
25                                      Belgium  2020  Domestic country     4792476
26                                      Belgium  2021  Domestic country     7728918
27                                      Belgium  2022  Domestic country     9406484
28                                      Belgium  2023  Domestic country     9296452
29                                      Belgium  2024  Domestic country     9278532
30                                     Bulgaria  2014  Domestic country     3154330
31                                     Bulgaria  2015  Domestic country     3414665
32                                     Bulgaria  2016  Domestic country     3809465
33                                     Bulgaria  2017  Domestic country     3805816
34                                     Bulgaria  2018  Domestic country     3889521
35                                     Bulgaria  2019  Domestic country     4120284
36                                     Bulgaria  2020  Domestic country     2847984
37                                     Bulgaria  2021  Domestic country     3754603
38                                     Bulgaria  2022  Domestic country     4551371
39                                     Bulgaria  2023  Domestic country     5019035
40                                     Bulgaria  2024  Domestic country     5212667
41                                      Croatia  2014  Domestic country     1444016
42                                      Croatia  2015  Domestic country     1613517
43                                      Croatia  2016  Domestic country     1739147
44                                      Croatia  2017  Domestic country     1828233
45                                      Croatia  2018  Domestic country     2013924
46                                      Croatia  2019  Domestic country     2205439
47                                      Croatia  2020  Domestic country     1452598
48                                      Croatia  2021  Domestic country     2130704
49                                      Croatia  2022  Domestic country     2446921
50                                      Croatia  2023  Domestic country     2632929
51                                      Croatia  2024  Domestic country     2862219
52                                       Cyprus  2014  Domestic country      433979
53                                       Cyprus  2015  Domestic country      441552
54                                       Cyprus  2016  Domestic country      461785
55                                       Cyprus  2017  Domestic country      457850
56                                       Cyprus  2018  Domestic country      511418
57                                       Cyprus  2019  Domestic country      553613
58                                       Cyprus  2020  Domestic country      572196
59                                       Cyprus  2021  Domestic country      713176
60                                       Cyprus  2022  Domestic country      648129
61                                       Cyprus  2023  Domestic country      628284
62                                       Cyprus  2024  Domestic country      686132
63                                      Czechia  2014  Domestic country     7491191
64                                      Czechia  2015  Domestic country     8488637
65                                      Czechia  2016  Domestic country     9067413
66                                      Czechia  2017  Domestic country     9840093
67                                      Czechia  2018  Domestic country    10635756
68                                      Czechia  2019  Domestic country    11107866
69                                      Czechia  2020  Domestic country     8052274
70                                      Czechia  2021  Domestic country     8813943
71                                      Czechia  2022  Domestic country    12080764
72                                      Czechia  2023  Domestic country    12418741
73                                      Czechia  2024  Domestic country    12332067
74                                      Denmark  2014  Domestic country     4243014
75                                      Denmark  2015  Domestic country     4533666
76                                      Denmark  2016  Domestic country     4751127
77                                      Denmark  2017  Domestic country     4801615
78                                      Denmark  2018  Domestic country     4935224
79                                      Denmark  2019  Domestic country     5192979
80                                      Denmark  2020  Domestic country     4129801
81                                      Denmark  2021  Domestic country     5232372
82                                      Denmark  2022  Domestic country     6207441
83                                      Denmark  2023  Domestic country     6091016
84                                      Denmark  2024  Domestic country     6043769
85                                      Estonia  2014  Domestic country     1103755
86                                      Estonia  2015  Domestic country     1182979
87                                      Estonia  2016  Domestic country     1268388
88                                      Estonia  2017  Domestic country     1388785
89                                      Estonia  2018  Domestic country     1450960
90                                      Estonia  2019  Domestic country     1536526
91                                      Estonia  2020  Domestic country     1296065
92                                      Estonia  2021  Domestic country     1575563
93                                      Estonia  2022  Domestic country     1785939
94                                      Estonia  2023  Domestic country     1755905
95                                      Estonia  2024  Domestic country     1755327
96    European Union - 27 countries (from 2020)  2014  Domestic country   486321742
97    European Union - 27 countries (from 2020)  2015  Domestic country   511049249
98    European Union - 27 countries (from 2020)  2016  Domestic country   530364067
99    European Union - 27 countries (from 2020)  2017  Domestic country   553608891
100   European Union - 27 countries (from 2020)  2018  Domestic country   572881772
101   European Union - 27 countries (from 2020)  2019  Domestic country   592903034
102   European Union - 27 countries (from 2020)  2020  Domestic country   354436909
103   European Union - 27 countries (from 2020)  2021  Domestic country   438301914
104   European Union - 27 countries (from 2020)  2022  Domestic country   583638931
105   European Union - 27 countries (from 2020)  2023  Domestic country   611071494
106   European Union - 27 countries (from 2020)  2024  Domestic country   618578934
107                                     Finland  2014  Domestic country     7928850
108                                     Finland  2015  Domestic country     8112802
109                                     Finland  2016  Domestic country     8319180
110                                     Finland  2017  Domestic country     8614140
111                                     Finland  2018  Domestic country     8742953
112                                     Finland  2019  Domestic country     9136439
113                                     Finland  2020  Domestic country     6446523
114                                     Finland  2021  Domestic country     8167713
115                                     Finland  2022  Domestic country     9405548
116                                     Finland  2023  Domestic country     9694934
117                                     Finland  2024  Domestic country     9550111
118                                      France  2014  Domestic country   106884663
119                                      France  2015  Domestic country   110695233
120                                      France  2016  Domestic country   112304511
121                                      France  2017  Domestic country   117911260
122                                      France  2018  Domestic country   118970003
123                                      France  2019  Domestic country   123048025
124                                      France  2020  Domestic country    76346861
125                                      France  2021  Domestic country    97081163
126                                      France  2022  Domestic country   122713921
127                                      France  2023  Domestic country   127317904
128                                      France  2024  Domestic country   126508114
129                                     Germany  2014  Domestic country   122068364
130                                     Germany  2015  Domestic country   126062735
131                                     Germany  2016  Domestic country   130218849
132                                     Germany  2017  Domestic country   135004792
133                                     Germany  2018  Domestic country   140494471
134                                     Germany  2019  Domestic country   145679435
135                                     Germany  2020  Domestic country    82691873
136                                     Germany  2021  Domestic country    82122347
137                                     Germany  2022  Domestic country   130157063
138                                     Germany  2023  Domestic country   143495379
139                                     Germany  2024  Domestic country   147267602
140                                      Greece  2014  Domestic country     7414809
141                                      Greece  2015  Domestic country     7665265
142                                      Greece  2016  Domestic country     8080042
143                                      Greece  2017  Domestic country     8142571
144                                      Greece  2018  Domestic country     9264746
145                                      Greece  2019  Domestic country     9163555
146                                      Greece  2020  Domestic country     4617211
147                                      Greece  2021  Domestic country     5652556
148                                      Greece  2022  Domestic country     8311888
149                                      Greece  2023  Domestic country     9505853
150                                      Greece  2024  Domestic country     9776628
151                                     Hungary  2014  Domestic country     5515165
152                                     Hungary  2015  Domestic country     5984739
153                                     Hungary  2016  Domestic country     6346301
154                                     Hungary  2017  Domestic country     6809296
155                                     Hungary  2018  Domestic country     7170933
156                                     Hungary  2019  Domestic country     7285514
157                                     Hungary  2020  Domestic country     4264303
158                                     Hungary  2021  Domestic country     4697535
159                                     Hungary  2022  Domestic country     6805889
160                                     Hungary  2023  Domestic country     6715790
161                                     Hungary  2024  Domestic country     7014437
162                                     Iceland  2014  Domestic country      699733
163                                     Iceland  2015  Domestic country      602016
164                                     Iceland  2016  Domestic country      646790
165                                     Iceland  2019  Domestic country      698737
166                                     Iceland  2020  Domestic country      890363
167                                     Iceland  2021  Domestic country     1190857
168                                     Iceland  2022  Domestic country     1253448
169                                     Iceland  2023  Domestic country     1273185
170                                     Ireland  2014  Domestic country     8120439
171                                     Ireland  2015  Domestic country     8088800
172                                     Ireland  2016  Domestic country     7382650
173                                     Ireland  2018  Domestic country     8970717
174                                     Ireland  2019  Domestic country     8640699
175                                     Ireland  2020  Domestic country     4118000
176                                     Ireland  2021  Domestic country     3100000
177                                     Ireland  2022  Domestic country     7256000
178                                     Ireland  2023  Domestic country     7452009
179                                     Ireland  2024  Domestic country     8459000
180                                       Italy  2014  Domestic country    54916852
181                                       Italy  2015  Domestic country    58352886
182                                       Italy  2016  Domestic country    60180004
183                                       Italy  2017  Domestic country    62672366
184                                       Italy  2018  Domestic country    64905729
185                                       Italy  2019  Domestic country    66371433
186                                       Italy  2020  Domestic country    39190227
187                                       Italy  2021  Domestic country    51767750
188                                       Italy  2022  Domestic country    63427781
189                                       Italy  2023  Domestic country    65758654
190                                       Italy  2024  Domestic country    65696652
191                                      Latvia  2014  Domestic country      667343
192                                      Latvia  2015  Domestic country      664628
193                                      Latvia  2016  Domestic country      730011
194                                      Latvia  2017  Domestic country      798365
195                                      Latvia  2018  Domestic country      883411
196                                      Latvia  2019  Domestic country      907414
197                                      Latvia  2020  Domestic country      747990
198                                      Latvia  2021  Domestic country      864400
199                                      Latvia  2022  Domestic country     1033196
200                                      Latvia  2023  Domestic country     1046823
201                                      Latvia  2024  Domestic country     1113409
202                               Liechtenstein  2014  Domestic country        1054
203                               Liechtenstein  2015  Domestic country         983
204                               Liechtenstein  2016  Domestic country        1670
205                               Liechtenstein  2017  Domestic country        1677
206                               Liechtenstein  2018  Domestic country        1781
207                               Liechtenstein  2019  Domestic country        1781
208                               Liechtenstein  2020  Domestic country        1332
209                               Liechtenstein  2021  Domestic country        2638
210                               Liechtenstein  2022  Domestic country        1699
211                               Liechtenstein  2023  Domestic country        2360
212                               Liechtenstein  2024  Domestic country        2798
213                                   Lithuania  2014  Domestic country     1316696
214                                   Lithuania  2015  Domestic country     1417321
215                                   Lithuania  2016  Domestic country     1546624
216                                   Lithuania  2017  Domestic country     1669403
217                                   Lithuania  2018  Domestic country     1875657
218                                   Lithuania  2019  Domestic country     2099777
219                                   Lithuania  2020  Domestic country     1615148
220                                   Lithuania  2021  Domestic country     1962633
221                                   Lithuania  2022  Domestic country     2675666
222                                   Lithuania  2023  Domestic country     2622501
223                                   Lithuania  2024  Domestic country     2656513
224                                  Luxembourg  2014  Domestic country      104417
225                                  Luxembourg  2015  Domestic country      113471
226                                  Luxembourg  2016  Domestic country      116915
227                                  Luxembourg  2017  Domestic country      131482
228                                  Luxembourg  2018  Domestic country      135711
229                                  Luxembourg  2019  Domestic country      139289
230                                  Luxembourg  2020  Domestic country      151783
231                                  Luxembourg  2021  Domestic country      153785
232                                  Luxembourg  2022  Domestic country      181576
233                                  Luxembourg  2023  Domestic country      183963
234                                  Luxembourg  2024  Domestic country      203446
235                                       Malta  2014  Domestic country      155378
236                                       Malta  2015  Domestic country      157267

In [743]:
arr.drop(arr[arr['country'] == "European Union - 27 countries (from 2020)"].index, inplace=True)
arr.reset_index(drop=True, inplace=True)

In [744]:
print(arr.to_string())

              country  year             resid   arrivals
0             Albania  2018  Domestic country     476294
1             Albania  2019  Domestic country     468787
2             Albania  2020  Domestic country     371523
3             Albania  2021  Domestic country     545835
4             Albania  2022  Domestic country     683467
5             Albania  2023  Domestic country     926803
6             Albania  2024  Domestic country     993348
7             Austria  2014  Domestic country   11400395
8             Austria  2015  Domestic country   11805718
9             Austria  2016  Domestic country   12413155
10            Austria  2017  Domestic country   12680617
11            Austria  2018  Domestic country   13087273
12            Austria  2019  Domestic country   13359120
13            Austria  2020  Domestic country    9034335
14            Austria  2021  Domestic country    8659900
15            Austria  2022  Domestic country   12695341
16            Austria  2023  Domestic country   13437243
17            Austria  2024  Domestic country   13669736
18            Austria  2025  Domestic country   13816162
19            Belgium  2014  Domestic country    6753644
20            Belgium  2015  Domestic country    7492173
21            Belgium  2016  Domestic country    7729359
22            Belgium  2017  Domestic country    7934684
23            Belgium  2018  Domestic country    8441061
24            Belgium  2019  Domestic country    8714287
25            Belgium  2020  Domestic country    4792476
26            Belgium  2021  Domestic country    7728918
27            Belgium  2022  Domestic country    9406484
28            Belgium  2023  Domestic country    9296452
29            Belgium  2024  Domestic country    9278532
30           Bulgaria  2014  Domestic country    3154330
31           Bulgaria  2015  Domestic country    3414665
32           Bulgaria  2016  Domestic country    3809465
33           Bulgaria  2017  Domestic country    3805816
34           Bulgaria  2018  Domestic country    3889521
35           Bulgaria  2019  Domestic country    4120284
36           Bulgaria  2020  Domestic country    2847984
37           Bulgaria  2021  Domestic country    3754603
38           Bulgaria  2022  Domestic country    4551371
39           Bulgaria  2023  Domestic country    5019035
40           Bulgaria  2024  Domestic country    5212667
41            Croatia  2014  Domestic country    1444016
42            Croatia  2015  Domestic country    1613517
43            Croatia  2016  Domestic country    1739147
44            Croatia  2017  Domestic country    1828233
45            Croatia  2018  Domestic country    2013924
46            Croatia  2019  Domestic country    2205439
47            Croatia  2020  Domestic country    1452598
48            Croatia  2021  Domestic country    2130704
49            Croatia  2022  Domestic country    2446921
50            Croatia  2023  Domestic country    2632929
51            Croatia  2024  Domestic country    2862219
52             Cyprus  2014  Domestic country     433979
53             Cyprus  2015  Domestic country     441552
54             Cyprus  2016  Domestic country     461785
55             Cyprus  2017  Domestic country     457850
56             Cyprus  2018  Domestic country     511418
57             Cyprus  2019  Domestic country     553613
58             Cyprus  2020  Domestic country     572196
59             Cyprus  2021  Domestic country     713176
60             Cyprus  2022  Domestic country     648129
61             Cyprus  2023  Domestic country     628284
62             Cyprus  2024  Domestic country     686132
63            Czechia  2014  Domestic country    7491191
64            Czechia  2015  Domestic country    8488637
65            Czechia  2016  Domestic country    9067413
66            Czechia  2017  Domestic country    9840093
67            Czechia  2018  Domestic country   10635756
68            Czechia  2019  Domestic country   11107866
69            Czechia  2020  Domestic country    8052274
70            Czechia  2021  Domestic country    8813943
71            Czechia  2022  Domestic country   12080764
72            Czechia  2023  Domestic country   12418741
73            Czechia  2024  Domestic country   12332067
74            Denmark  2014  Domestic country    4243014
75            Denmark  2015  Domestic country    4533666
76            Denmark  2016  Domestic country    4751127
77            Denmark  2017  Domestic country    4801615
78            Denmark  2018  Domestic country    4935224
79            Denmark  2019  Domestic country    5192979
80            Denmark  2020  Domestic country    4129801
81            Denmark  2021  Domestic country    5232372
82            Denmark  2022  Domestic country    6207441
83            Denmark  2023  Domestic country    6091016
84            Denmark  2024  Domestic country    6043769
85            Estonia  2014  Domestic country    1103755
86            Estonia  2015  Domestic country    1182979
87            Estonia  2016  Domestic country    1268388
88            Estonia  2017  Domestic country    1388785
89            Estonia  2018  Domestic country    1450960
90            Estonia  2019  Domestic country    1536526
91            Estonia  2020  Domestic country    1296065
92            Estonia  2021  Domestic country    1575563
93            Estonia  2022  Domestic country    1785939
94            Estonia  2023  Domestic country    1755905
95            Estonia  2024  Domestic country    1755327
96            Finland  2014  Domestic country    7928850
97            Finland  2015  Domestic country    8112802
98            Finland  2016  Domestic country    8319180
99            Finland  2017  Domestic country    8614140
100           Finland  2018  Domestic country    8742953
101           Finland  2019  Domestic country    9136439
102           Finland  2020  Domestic country    6446523
103           Finland  2021  Domestic country    8167713
104           Finland  2022  Domestic country    9405548
105           Finland  2023  Domestic country    9694934
106           Finland  2024  Domestic country    9550111
107            France  2014  Domestic country  106884663
108            France  2015  Domestic country  110695233
109            France  2016  Domestic country  112304511
110            France  2017  Domestic country  117911260
111            France  2018  Domestic country  118970003
112            France  2019  Domestic country  123048025
113            France  2020  Domestic country   76346861
114            France  2021  Domestic country   97081163
115            France  2022  Domestic country  122713921
116            France  2023  Domestic country  127317904
117            France  2024  Domestic country  126508114
118           Germany  2014  Domestic country  122068364
119           Germany  2015  Domestic country  126062735
120           Germany  2016  Domestic country  130218849
121           Germany  2017  Domestic country  135004792
122           Germany  2018  Domestic country  140494471
123           Germany  2019  Domestic country  145679435
124           Germany  2020  Domestic country   82691873
125           Germany  2021  Domestic country   82122347
126           Germany  2022  Domestic country  130157063
127           Germany  2023  Domestic country  143495379
128           Germany  2024  Domestic country  147267602
129            Greece  2014  Domestic country    7414809
130            Greece  2015  Domestic country    7665265
131            Greece  2016  Domestic country    8080042
132            Greece  2017  Domestic country    8142571
133            Greece  2018  Domestic country    9264746
134            Greece  2019  Domestic country    9163555
135            Greece  2020  Domestic country    4617211
136            Greece  2021  Domestic country    5652556
137            Greece  2022  Domestic country    8311888
138            Greece  2023  Domestic country    9505853
139            Greece  2024  Domestic country    9776628
140           Hungary  2014  Domestic country    5515165
141           Hungary  2015  Domestic country    5984739
142           Hungary  2016  Domestic country    6346301
143           Hungary  2017  Domestic country    6809296
144           Hungary  2018  Domestic country    7170933
145           Hungary  2019  Domestic country    7285514
146           Hungary  2020  Domestic country    4264303
147           Hungary  2021  Domestic country    4697535
148           Hungary  2022  Domestic country    6805889
149           Hungary  2023  Domestic country    6715790
150           Hungary  2024  Domestic country    7014437
151           Iceland  2014  Domestic country     699733
152           Iceland  2015  Domestic country     602016
153           Iceland  2016  Domestic country     646790
154           Iceland  2019  Domestic country     698737
155           Iceland  2020  Domestic country     890363
156           Iceland  2021  Domestic country    1190857
157           Iceland  2022  Domestic country    1253448
158           Iceland  2023  Domestic country    1273185
159           Ireland  2014  Domestic country    8120439
160           Ireland  2015  Domestic country    8088800
161           Ireland  2016  Domestic country    7382650
162           Ireland  2018  Domestic country    8970717
163           Ireland  2019  Domestic country    8640699
164           Ireland  2020  Domestic country    4118000
165           Ireland  2021  Domestic country    3100000
166           Ireland  2022  Domestic country    7256000
167           Ireland  2023  Domestic country    7452009
168           Ireland  2024  Domestic country    8459000
169             Italy  2014  Domestic country   54916852
170             Italy  2015  Domestic country   58352886
171             Italy  2016  Domestic country   60180004
172             Italy  2017  Domestic country   62672366
173             Italy  2018  Domestic country   64905729
174             Italy  2019  Domestic country   66371433
175             Italy  2020  Domestic country   39190227
176             Italy  2021  Domestic country   51767750
177             Italy  2022  Domestic country   63427781
178             Italy  2023  Domestic country   65758654
179             Italy  2024  Domestic country   65696652
180            Latvia  2014  Domestic country     667343
181            Latvia  2015  Domestic country     664628
182            Latvia  2016  Domestic country     730011
183            Latvia  2017  Domestic country     798365
184            Latvia  2018  Domestic country     883411
185            Latvia  2019  Domestic country     907414
186            Latvia  2020  Domestic country     747990
187            Latvia  2021  Domestic country     864400
188            Latvia  2022  Domestic country    1033196
189            Latvia  2023  Domestic country    1046823
190            Latvia  2024  Domestic country    1113409
191     Liechtenstein  2014  Domestic country       1054
192     Liechtenstein  2015  Domestic country        983
193     Liechtenstein  2016  Domestic country       1670
194     Liechtenstein  2017  Domestic country       1677
195     Liechtenstein  2018  Domestic country       1781
196     Liechtenstein  2019  Domestic country       1781
197     Liechtenstein  2020  Domestic country       1332
198     Liechtenstein  2021  Domestic country       2638
199     Liechtenstein  2022  Domestic country       1699
200     Liechtenstein  2023  Domestic country       2360
201     Liechtenstein  2024  Domestic country       2798
202         Lithuania  2014  Domestic country    1316696
203         Lithuania  2015  Domestic country    1417321
204         Lithuania  2016  Domestic country    1546624
205         Lithuania  2017  Domestic country    1669403
206         Lithuania  2018  Domestic country    1875657
207         Lithuania  2019  Domestic country    2099777
208         Lithuania  2020  Domestic country    1615148
209         Lithuania  2021  Domestic country    1962633
210         Lithuania  2022  Domestic country    2675666
211         Lithuania  2023  Domestic country    2622501
212         Lithuania  2024  Domestic country    2656513
213        Luxembourg  2014  Domestic country     104417
214        Luxembourg  2015  Domestic country     113471
215        Luxembourg  2016  Domestic country     116915
216        Luxembourg  2017  Domestic country     131482
217        Luxembourg  2018  Domestic country     135711
218        Luxembourg  2019  Domestic country     139289
219        Luxembourg  2020  Domestic country     151783
220        Luxembourg  2021  Domestic country     153785
221        Luxembourg  2022  Domestic country     181576
222        Luxembourg  2023  Domestic country     183963
223        Luxembourg  2024  Domestic country     203446
224             Malta  2014  Domestic country     155378
225             Malta  2015  Domestic country     157267
226             Malta  2016  Domestic country     151389
227             Malta  2017  Domestic country     167109
228             Malta  2018  Domestic country     184577
229             Malta  2019  Domestic country     201076
230             Malta  2020  Domestic country     219321
231             Malta  2021  Domestic country     245245
232             Malta  2022  Domestic country     254512
233             Malta  2023  Domestic country     259363
234             Malta  2024  Domestic country     271588
235        Montenegro  2015  Domestic country     153185
236        Montenegro  2016  Domestic country     151696
237        Montenegro  2017  Domestic country     111890
238        Montenegro  2022  Domestic country     140333
239        Montenegro  2023  Domestic country     158021
240        Montenegro  2024  Domestic country     167140
241       Netherlands  2014  Domestic country   21931193
242       Netherlands  2015  Domestic country   22311303
243       Netherlands  2016  Domestic country   23053578
244       Netherlands  2017  Domestic country   24310943
245       Netherlands  2018  Domestic country   25132289
246       Netherlands  2019  Domestic country   25786602
247       Netherlands  2020  Domestic country   20035412
248       Netherlands  2021  Domestic country   25472295
249       Netherlands  2022  Domestic country   29417995
250       Netherlands  2023  Domestic country   29100201
251       Netherlands  2024  Domestic country   30012347
252   North Macedonia  2014  Domestic country     207572
253   North Macedonia  2015  Domestic country     219532
254   North Macedonia  2016  Domestic country     228882
255   North Macedonia  2017  Domestic country     242674
256   North Macedonia  2018  Domestic country     268612
257   North Macedonia  2019  Domestic country     276091
258   North Macedonia  2020  Domestic country     233969
259   North Macedonia  2021  Domestic country     251830
260   North Macedonia  2022  Domestic country     261898
261   North Macedonia  2023  Domestic country     266035
262   North Macedonia  2024  Domestic country     255652
263            Norway  2014  Domestic country   13824254
264            Norway  2015  Domestic country   14029604
265            Norway  2016  Domestic country   14673056
266            Norway  2020  Domestic country   10034858
267            Norway  2021  Domestic country   11149706
268            Norway  2022  Domestic country   13133328
269            Norway  2023  Domestic country   13353220
270            Norway  2024  Domestic country   13492337
271            Poland  2014  Domestic country   19613643
272            Poland  2015  Domestic country   21252486
273            Poland  2016  Domestic country   23729515
274            Poland  2017  Domestic country   25185677
275            Poland  2018  Domestic country   26813699
276            Poland  2019  Domestic country   28197545
277            Poland  2020  Domestic country   15615208
278            Poland  2021  Domestic country   19689140
279            Poland  2022  Domestic country   28402393
280            Poland  2023  Domestic country   29164646
281            Poland  2024  Domestic country   30966882
282          Portugal  2014  Domestic country    8213985
283          Portugal  2015  Domestic country    8940270
284          Portugal  2016  Domestic country    9572917
285          Portugal  2017  Domestic country   10257547
286          Portugal  2018  Domestic country   10830619
287          Portugal  2019  Domestic country   11694640
288          Portugal  2020  Domestic country    7130802
289          Portugal  2021  Domestic country    9190822
290          Portugal  2022  Domestic country   12009431
291          Portugal  2023  Domestic country   12611122
292          Portugal  2024  Domestic country   13008522
293           Romania  2014  Domestic country    6532213
294           Romania  2015  Domestic country    7664325
295           Romania  2016  Domestic country    8445821
296           Romania  2017  Domestic country    9306915
297           Romania  2018  Domestic country   10029531
298           Romania  2019  Domestic country   10604562
299           Romania  2020  Domestic country    5886981
300           Romania  2021  Domestic country    9168707
301           Romania  2022  Domestic country   10712281
302           Romania  2023  Domestic country   11562950
303           Romania  2024  Domestic country   11894934
304            Serbia  2014  Domestic country    1125645
305            Serbia  2015  Domestic country    1281983
306            Serbia  2016  Domestic country    1445608
307            Serbia  2020  Domestic country    1372257
308            Serbia  2021  Domestic country    1718454
309            Serbia  2022  Domestic country    2096472
310            Serbia  2023  Domestic country    2058492
311            Serbia  2024  Domestic country    2048016
312          Slovakia  2014  Domestic country    2229662
313          Slovakia  2015  Domestic country    2573289
314          Slovakia  2016  Domestic country    2948498
315          Slovakia  2017  Domestic country    3158266
316          Slovakia  2018  Domestic country    3273224
317          Slovakia  2019  Domestic country    3858686
318          Slovakia  2020  Domestic country    2271926
319          Slovakia  2021  Domestic country    2077005
320          Slovakia  2022  Domestic country    3145423
321          Slovakia  2023  Domestic country    3527332
322          Slovakia  2024  Domestic country    3630850
323          Slovenia  2014  Domestic country    1100862
324          Slovenia  2015  Domestic country    1209019
325          Slovenia  2016  Domestic country    1273017
326          Slovenia  2017  Domestic country    1348977
327          Slovenia  2019  Domestic country    1527029
328          Slovenia  2020  Domestic country    1847384
329          Slovenia  2021  Domestic country    2169165
330          Slovenia  2022  Domestic country    1931242
331          Slovenia  2023  Domestic country    1533827
332          Slovenia  2024  Domestic country    1528953
333             Spain  2014  Domestic country   55185879
334             Spain  2015  Domestic country   59021796
335             Spain  2016  Domestic country   62199939
336             Spain  2017  Domestic country   64159337
337             Spain  2018  Domestic country   65032598
338             Spain  2019  Domestic country   67280725
339             Spain  2020  Domestic country   32225935
340             Spain  2021  Domestic country   55069349
341             Spain  2022  Domestic country   70542990
342             Spain  2023  Domestic country   72690996
343             Spain  2024  Domestic country   71997969
344            Sweden  2014  Domestic country   20397005
345            Sweden  2015  Domestic country   21788707
346            Sweden  2016  Domestic country   22524467
347            Sweden  2017  Domestic country   23033004
348            Sweden  2018  Domestic country   23519609

In [745]:
arr.dtypes

country       str
year        int64
resid         str
arrivals    int64
dtype: object

In [746]:
arrivals_wide = arr.pivot_table(
    index=["country", "year"],
    columns="resid",
    values="arrivals",
    aggfunc="sum"
).reset_index()

In [747]:
arrivals_wide = arrivals_wide.rename(columns={
    "Domestic country": "arrivals_dom",
    "Foreign country": "arrivals_for",
    "Total": "arrivals_tot"
})

In [748]:
arrivals_wide = arrivals_wide[[
    "country",
    "year",
    "arrivals_dom",
    "arrivals_for",
    "arrivals_tot"
]]

In [749]:
arrivals_wide = arrivals_wide.sort_values(["country", "year"]).reset_index(drop=True)

In [750]:
print(arrivals_wide.to_string())

resid          country  year  arrivals_dom  arrivals_for  arrivals_tot
0              Albania  2018      476294.0      766467.0     1242761.0
1              Albania  2019      468787.0      784709.0     1253496.0
2              Albania  2020      371523.0      293657.0      665180.0
3              Albania  2021      545835.0      685081.0     1230916.0
4              Albania  2022      683467.0      886515.0     1569982.0
5              Albania  2023      926803.0     1409327.0     2336130.0
6              Albania  2024      993348.0     2185093.0     3178441.0
7              Austria  2014    11400395.0    22246197.0    33646592.0
8              Austria  2015    11805718.0    23544384.0    35350102.0
9              Austria  2016    12413155.0    24677596.0    37090751.0
10             Austria  2017    12680617.0    25906005.0    38586622.0
11             Austria  2018    13087273.0    27006207.0    40093480.0
12             Austria  2019    13359120.0    27962315.0    41321435.0
13             Austria  2020     9034335.0    12637309.0    21671644.0
14             Austria  2021     8659900.0    11098084.0    19757984.0
15             Austria  2022    12695341.0    22874333.0    35569674.0
16             Austria  2023    13437243.0    27212813.0    40650056.0
17             Austria  2024    13669736.0    28498633.0    42168369.0
18             Austria  2025    13816162.0    29764173.0    43580335.0
19             Belgium  2014     6753644.0     7887426.0    14641070.0
20             Belgium  2015     7492173.0     8354753.0    15846926.0
21             Belgium  2016     7729359.0     7481422.0    15210781.0
22             Belgium  2017     7934684.0     8384573.0    16319257.0
23             Belgium  2018     8441061.0     9118854.0    17559915.0
24             Belgium  2019     8714287.0     9343324.0    18057611.0
25             Belgium  2020     4792476.0     2583941.0     7376417.0
26             Belgium  2021     7728918.0     3243053.0    10971971.0
27             Belgium  2022     9406484.0     8220161.0    17626645.0
28             Belgium  2023     9296452.0     9279571.0    18576023.0
29             Belgium  2024     9278532.0     9638187.0    18916719.0
30            Bulgaria  2014     3154330.0     2791578.0     5945908.0
31            Bulgaria  2015     3414665.0     2864371.0     6279036.0
32            Bulgaria  2016     3809465.0     3386932.0     7196397.0
33            Bulgaria  2017     3805816.0     3655830.0     7461646.0
34            Bulgaria  2018     3889521.0     3910159.0     7799680.0
35            Bulgaria  2019     4120284.0     4067350.0     8187634.0
36            Bulgaria  2020     2847984.0     1175779.0     4023763.0
37            Bulgaria  2021     3754603.0     1893031.0     5647634.0
38            Bulgaria  2022     4551371.0     3069863.0     7621234.0
39            Bulgaria  2023     5019035.0     3621413.0     8640448.0
40            Bulgaria  2024     5212667.0     3770036.0     8982703.0
41             Croatia  2014     1444016.0    11438806.0    12882822.0
42             Croatia  2015     1613517.0    12543509.0    14157026.0
43             Croatia  2016     1739147.0    13707444.0    15446591.0
44             Croatia  2017     1828233.0    15581704.0    17409937.0
45             Croatia  2018     2013924.0    16635013.0    18648937.0
46             Croatia  2019     2205439.0    17348056.0    19553495.0
47             Croatia  2020     1452598.0     5544784.0     6997382.0
48             Croatia  2021     2130704.0    10640050.0    12770754.0
49             Croatia  2022     2446921.0    15322224.0    17769145.0
50             Croatia  2023     2632929.0    16853644.0    19486573.0
51             Croatia  2024     2862219.0    17377097.0    20239316.0
52              Cyprus  2014      433979.0     1935641.0     2369620.0
53              Cyprus  2015      441552.0     1874323.0     2315875.0
54              Cyprus  2016      461785.0     2268176.0     2729961.0
55              Cyprus  2017      457850.0     2488611.0     2946461.0
56              Cyprus  2018      511418.0     2665743.0     3177161.0
57              Cyprus  2019      553613.0     2689344.0     3242957.0
58              Cyprus  2020      572196.0      532322.0     1104518.0
59              Cyprus  2021      713176.0     1404355.0     2117531.0
60              Cyprus  2022      648129.0     2174270.0     2822399.0
61              Cyprus  2023      628284.0     2537250.0     3165534.0
62              Cyprus  2024      686132.0     3030161.0     3716293.0
63             Czechia  2014     7491191.0     8095885.0    15587076.0
64             Czechia  2015     8488637.0     8706913.0    17195550.0
65             Czechia  2016     9067413.0     9321440.0    18388853.0
66             Czechia  2017     9840093.0    10160468.0    20000561.0
67             Czechia  2018    10635756.0    10611394.0    21247150.0
68             Czechia  2019    11107866.0    10890500.0    21998366.0
69             Czechia  2020     8052274.0     2784170.0    10836444.0
70             Czechia  2021     8813943.0     2569658.0    11383601.0
71             Czechia  2022    12080764.0     7343400.0    19424164.0
72             Czechia  2023    12418741.0     9558930.0    21977671.0
73             Czechia  2024    12332067.0    10477528.0    22809595.0
74             Denmark  2014     4243014.0     2465447.0     6708461.0
75             Denmark  2015     4533666.0     2630938.0     7164604.0
76             Denmark  2016     4751127.0     2767651.0     7518778.0
77             Denmark  2017     4801615.0     2871593.0     7673208.0
78             Denmark  2018     4935224.0     3031450.0     7966674.0
79             Denmark  2019     5192979.0     3086408.0     8279387.0
80             Denmark  2020     4129801.0      906032.0     5035833.0
81             Denmark  2021     5232372.0     1185156.0     6417528.0
82             Denmark  2022     6207441.0     3010487.0     9217928.0
83             Denmark  2023     6091016.0     3319653.0     9410669.0
84             Denmark  2024     6043769.0     3627423.0     9671192.0
85             Estonia  2014     1103755.0     1983315.0     3087070.0
86             Estonia  2015     1182979.0     1929164.0     3112143.0
87             Estonia  2016     1268388.0     2056526.0     3324914.0
88             Estonia  2017     1388785.0     2156147.0     3544932.0
89             Estonia  2018     1450960.0     2140535.0     3591495.0
90             Estonia  2019     1536526.0     2253429.0     3789955.0
91             Estonia  2020     1296065.0      676066.0     1972131.0
92             Estonia  2021     1575563.0      562783.0     2138346.0
93             Estonia  2022     1785939.0     1466959.0     3252898.0
94             Estonia  2023     1755905.0     1669825.0     3425730.0
95             Estonia  2024     1755327.0     1855063.0     3610390.0
96             Finland  2014     7928850.0     2731256.0    10660106.0
97             Finland  2015     8112802.0     2622039.0    10734841.0
98             Finland  2016     8319180.0     2788903.0    11108083.0
99             Finland  2017     8614140.0     3180254.0    11794394.0
100            Finland  2018     8742953.0     3224164.0    11967117.0
101            Finland  2019     9136439.0     3290238.0    12426677.0
102            Finland  2020     6446523.0      895577.0     7342100.0
103            Finland  2021     8167713.0      806962.0     8974675.0
104            Finland  2022     9405548.0     2127475.0    11533023.0
105            Finland  2023     9694934.0     2560523.0    12255457.0
106            Finland  2024     9550111.0     2903960.0    12454071.0
107             France  2014   106884663.0    46073942.0   152958605.0
108             France  2015   110695233.0    46797708.0   157492941.0
109             France  2016   112304511.0    44958968.0   157263479.0
110             France  2017   117911260.0    48919374.0   166830634.0
111             France  2018   118970003.0    52505891.0   171475894.0
112             France  2019   123048025.0    51580030.0   174628055.0
113             France  2020    76346861.0    15542906.0    91889767.0
114             France  2021    97081163.0    20361179.0   117442342.0
115             France  2022   122713921.0    46221455.0   168935376.0
116             France  2023   127317904.0    53412105.0   180730009.0
117             France  2024   126508114.0    54591535.0   181099649.0
118            Germany  2014   122068364.0    32859540.0   154927904.0
119            Germany  2015   126062735.0    34831012.0   160893747.0
120            Germany  2016   130218849.0    35404924.0   165623773.0
121            Germany  2017   135004792.0    37307331.0   172312123.0
122            Germany  2018   140494471.0    38747698.0   179242169.0
123            Germany  2019   145679435.0    39441607.0   185121042.0
124            Germany  2020    82691873.0    12410850.0    95102723.0
125            Germany  2021    82122347.0    11652076.0    93774423.0
126            Germany  2022   130157063.0    28382919.0   158539982.0
127            Germany  2023   143495379.0    34711761.0   178207140.0
128            Germany  2024   147267602.0    37419799.0   184687401.0
129             Greece  2014     7414809.0    15259242.0    22674051.0
130             Greece  2015     7665265.0    16501709.0    24166974.0
131             Greece  2016     8080042.0    16915996.0    24996038.0
132             Greece  2017     8142571.0    19068697.0    27211268.0
133             Greece  2018     9264746.0    24320893.0    33585639.0
134             Greece  2019     9163555.0    25038498.0    34202053.0
135             Greece  2020     4617211.0     5487025.0    10104236.0
136             Greece  2021     5652556.0    12362791.0    18015347.0
137             Greece  2022     8311888.0    23101468.0    31413356.0
138             Greece  2023     9505853.0    26276571.0    35782424.0
139             Greece  2024     9776628.0    27376639.0    37153267.0
140            Hungary  2014     5515165.0     4617751.0    10132916.0
141            Hungary  2015     5984739.0     4928511.0    10913250.0
142            Hungary  2016     6346301.0     5301843.0    11648144.0
143            Hungary  2017     6809296.0     5650077.0    12459373.0
144            Hungary  2018     7170933.0     5945123.0    13116056.0
145            Hungary  2019     7285514.0     6168576.0    13454090.0
146            Hungary  2020     4264303.0     1366412.0     5630715.0
147            Hungary  2021     4697535.0     1868335.0     6565870.0
148            Hungary  2022     6805889.0     4481310.0    11287199.0
149            Hungary  2023     6715790.0     5487087.0    12202877.0
150            Hungary  2024     7014437.0     6113954.0    13128391.0
151            Iceland  2014      699733.0     2596740.0     3296473.0
152            Iceland  2015      602016.0     3376068.0     3978084.0
153            Iceland  2016      646790.0     3977547.0     4624337.0
154            Iceland  2019      698737.0     4533098.0     5231835.0
155            Iceland  2020      890363.0     1040869.0     1931232.0
156            Iceland  2021     1190857.0     1903026.0     3093883.0
157            Iceland  2022     1253448.0     4076435.0     5329883.0
158            Iceland  2023     1273185.0     4815055.0     6088240.0
159            Ireland  2014     8120439.0     2242815.0    10363254.0
160            Ireland  2015     8088800.0     2666848.0    10755648.0
161            Ireland  2016     7382650.0     3172440.0    10555090.0
162            Ireland  2018     8970717.0     3289489.0    12260206.0
163            Ireland  2019     8640699.0     3277804.0    11918503.0
164            Ireland  2020     4118000.0      706004.0     4824004.0
165            Ireland  2021     3100000.0      738622.0     3838622.0
166            Ireland  2022     7256000.0     2668012.0     9924012.0
167            Ireland  2023     7452009.0     3835670.0    11287679.0
168            Ireland  2024     8459000.0     4203374.0    12662374.0
169              Italy  2014    54916852.0    51635500.0   106552352.0
170              Italy  2015    58352886.0    55039251.0   113392137.0
171              Italy  2016    60180004.0    56764239.0   116944243.0
172              Italy  2017    62672366.0    60523190.0   123195556.0
173              Italy  2018    64905729.0    63195203.0   128100932.0
174              Italy  2019    66371433.0    65010220.0   131381653.0
175              Italy  2020    39190227.0    16511911.0    55702138.0
176              Italy  2021    51767750.0    26903217.0    78670967.0
177              Italy  2022    63427781.0    55086852.0   118514633.0
178              Italy  2023    65758654.0    67878055.0   133636709.0
179              Italy  2024    65696652.0    73951291.0   139647943.0
180             Latvia  2014      667343.0     1431038.0     2098381.0
181             Latvia  2015      664628.0     1474765.0     2139393.0
182             Latvia  2016      730011.0     1573632.0     2303643.0
183             Latvia  2017      798365.0     1778973.0     2577338.0
184             Latvia  2018      883411.0     1925397.0     2808808.0
185             Latvia  2019      907414.0     1945919.0     2853333.0
186             Latvia  2020      747990.0      714975.0     1462965.0
187             Latvia  2021      864400.0      442188.0     1306588.0
188             Latvia  2022     1033196.0     1138873.0     2172069.0
189             Latvia  2023     1046823.0     1388972.0     2435795.0
190             Latvia  2024     1113409.0     1587158.0     2700567.0
191      Liechtenstein  2014        1054.0       61251.0       62305.0
192      Liechtenstein  2015         983.0       56666.0       57649.0
193      Liechtenstein  2016        1670.0       69084.0       70754.0
194      Liechtenstein  2017        1677.0       79262.0       80939.0
195      Liechtenstein  2018        1781.0       85283.0       87064.0
196      Liechtenstein  2019        1781.0       98110.0       99891.0
197      Liechtenstein  2020        1332.0       58359.0       59691.0
198      Liechtenstein  2021        2638.0       70764.0       73402.0
199      Liechtenstein  2022        1699.0      100814.0      102513.0
200      Liechtenstein  2023        2360.0      114399.0      116759.0
201      Liechtenstein  2024        2798.0      117789.0      120587.0
202          Lithuania  2014     1316696.0     1356835.0     2673531.0
203          Lithuania  2015     1417321.0     1388487.0     2805808.0
204          Lithuania  2016     1546624.0     1517890.0     3064514.0
205          Lithuania  2017     1669403.0     1583801.0     3253204.0
206          Lithuania  2018     1875657.0     1744733.0     3620390.0
207          Lithuania  2019     2099777.0     1937972.0     4037749.0
208          Lithuania  2020     1615148.0      511566.0     2126714.0
209          Lithuania  2021     1962633.0      505361.0     2467994.0
210          Lithuania  2022     2675666.0     1149537.0     3825203.0
211          Lithuania  2023     2622501.0     1369549.0     3992050.0
212          Lithuania  2024     2656513.0     1449052.0     4105565.0
213         Luxembourg  2014      104417.0     1038475.0     1142892.0
214         Luxembourg  2015      113471.0     1150913.0     1264384.0
215         Luxembourg  2016      116915.0     1166258.0     1283173.0
216         Luxembourg  2017      131482.0     1159497.0     1290979.0
217         Luxembourg  2018      135711.0     1141038.0     1276749.0
218         Luxembourg  2019      139289.0     1186374.0     1325663.0
219         Luxembourg  2020      151783.0      473388.0      625171.0
220         Luxembourg  2021      153785.0      683259.0      837044.0
221         Luxembourg  2022      181576.0     1132054.0     1313630.0
222         Luxembourg  2023      183963.0     1258072.0     1442035.0
223         Luxembourg  2024      203446.0     1364853.0     1568299.0
224              Malta  2014      155378.0     1399301.0     1554679.0
225              Malta  2015      157267.0     1428801.0     1586068.0
226              Malta  2016      151389.0     1468143.0     1619532.0
227              Malta  2017      167109.0     1662358.0     1829467.0
228              Malta  2018      184577.0     1798002.0     1982579.0
229              Malta  2019      201076.0     1821836.0     2022912.0
230              Malta  2020      219321.0      486393.0      705714.0
231              Malta  2021      245245.0      736742.0      981987.0
232              Malta  2022      254512.0     1559649.0     1814161.0
233              Malta  2023      259363.0     1992637.0     2252000.0
234              Malta  2024      271588.0     2278803.0     2550391.0
235         Montenegro  2015      153185.0     1559924.0     1713109.0
236         Montenegro  2016      151696.0     1662121.0     1813817.0
237         Montenegro  2017      111890.0      843609.0      955499.0
238         Montenegro  2022      140333.0     1025642.0     1165975.0
239         Montenegro  2023      158021.0     1278125.0     1436146.0
240         Montenegro  2024      167140.0     1279340.0     1446480.0
241        Netherlands  2014    21931193.0    13924881.0    35856074.0
242        Netherlands  2015    22311303.0    15007135.0    37318438.0
243        Netherlands  2016    23053578.0    15829488.0    38883066.0
244        Netherlands  2017    24310943.0    17924191.0    42235134.0
245        Netherlands  2018    25132289.0    18780326.0    43912615.0
246        Netherlands  2019    25786602.0    20129400.0    45916002.0
247        Netherlands  2020    20035412.0     7265370.0    27300782.0
248        Netherlands  2021    25472295.0     6248089.0    31720384.0
249        Netherlands  2022    29417995.0    16582261.0    46000256.0
250        Netherlands  2023    29100201.0    20303590.0    49403791.0
251        Netherlands  2024    30012347.0    21253245.0    51265592.0
252    North Macedonia  2014      207572.0      417090.0      624662.0
253    North Macedonia  2015      219532.0      479152.0      698684.0
254    North Macedonia  2016      228882.0      508300.0      737182.0
255    North Macedonia  2017      242674.0      626879.0      869553.0
256    North Macedonia  2018      268612.0      702833.0      971445.0
257    North Macedonia  2019      276091.0      755438.0     1031529.0
258    North Macedonia  2020      233969.0      118101.0      352070.0
259    North Macedonia  2021      251830.0      293919.0      545749.0
260    North Macedonia  2022      261898.0      537037.0      798935.0
261    North Macedonia  2023      266035.0      733441.0      999476.0
262    North Macedonia  2024      255652.0      829599.0     1085251.0
263             Norway  2014    13824254.0     4854610.0    18678864.0
264             Norway  2015    14029604.0     5303531.0    19333135.0
265             Norway  2016    14673056.0     5920859.0    20593915.0
266             Norway  2020    10034858.0     1387137.0    11421995.0
267             Norway  2021    11149706.0     1435366.0    12585072.0
268             Norway  2022    13133328.0     4979438.0    18112766.0
269             Norway  2023    13353220.0     5951367.0    19304587.0
270             Norway  2024    13492337.0     6670410.0    20162747.0
271             Poland  2014    19613643.0     5470335.0    25083978.0
272             Poland  2015    21252486.0     5689570.0    26942056.0
273             Poland  2016    23729515.0     6378793.0    30108308.0
274             Poland  2017    25185677.0     6803667.0    31989344.0
275             Poland  2018    26813699.0     7082231.0    33895930.0
276             Poland  2019    28197545.0     7470546.0    35668091.0
277             Poland  2020    15615208.0     2263761.0    17878969.0
278             Poland  2021    19689140.0     2509832.0    22198972.0
279             Poland  2022    28402393.0     5846611.0    34249004.0

In [751]:
cols = ["arrivals_tot", "arrivals_dom", "arrivals_for"]
arrivals_wide[cols] = arrivals_wide[cols].astype("Int64")
arrivals_wide.columns.name = None

In [752]:
print(arrivals_wide.to_string())

             country  year  arrivals_dom  arrivals_for  arrivals_tot
0            Albania  2018        476294        766467       1242761
1            Albania  2019        468787        784709       1253496
2            Albania  2020        371523        293657        665180
3            Albania  2021        545835        685081       1230916
4            Albania  2022        683467        886515       1569982
5            Albania  2023        926803       1409327       2336130
6            Albania  2024        993348       2185093       3178441
7            Austria  2014      11400395      22246197      33646592
8            Austria  2015      11805718      23544384      35350102
9            Austria  2016      12413155      24677596      37090751
10           Austria  2017      12680617      25906005      38586622
11           Austria  2018      13087273      27006207      40093480
12           Austria  2019      13359120      27962315      41321435
13           Austria  2020       9034335      12637309      21671644
14           Austria  2021       8659900      11098084      19757984
15           Austria  2022      12695341      22874333      35569674
16           Austria  2023      13437243      27212813      40650056
17           Austria  2024      13669736      28498633      42168369
18           Austria  2025      13816162      29764173      43580335
19           Belgium  2014       6753644       7887426      14641070
20           Belgium  2015       7492173       8354753      15846926
21           Belgium  2016       7729359       7481422      15210781
22           Belgium  2017       7934684       8384573      16319257
23           Belgium  2018       8441061       9118854      17559915
24           Belgium  2019       8714287       9343324      18057611
25           Belgium  2020       4792476       2583941       7376417
26           Belgium  2021       7728918       3243053      10971971
27           Belgium  2022       9406484       8220161      17626645
28           Belgium  2023       9296452       9279571      18576023
29           Belgium  2024       9278532       9638187      18916719
30          Bulgaria  2014       3154330       2791578       5945908
31          Bulgaria  2015       3414665       2864371       6279036
32          Bulgaria  2016       3809465       3386932       7196397
33          Bulgaria  2017       3805816       3655830       7461646
34          Bulgaria  2018       3889521       3910159       7799680
35          Bulgaria  2019       4120284       4067350       8187634
36          Bulgaria  2020       2847984       1175779       4023763
37          Bulgaria  2021       3754603       1893031       5647634
38          Bulgaria  2022       4551371       3069863       7621234
39          Bulgaria  2023       5019035       3621413       8640448
40          Bulgaria  2024       5212667       3770036       8982703
41           Croatia  2014       1444016      11438806      12882822
42           Croatia  2015       1613517      12543509      14157026
43           Croatia  2016       1739147      13707444      15446591
44           Croatia  2017       1828233      15581704      17409937
45           Croatia  2018       2013924      16635013      18648937
46           Croatia  2019       2205439      17348056      19553495
47           Croatia  2020       1452598       5544784       6997382
48           Croatia  2021       2130704      10640050      12770754
49           Croatia  2022       2446921      15322224      17769145
50           Croatia  2023       2632929      16853644      19486573
51           Croatia  2024       2862219      17377097      20239316
52            Cyprus  2014        433979       1935641       2369620
53            Cyprus  2015        441552       1874323       2315875
54            Cyprus  2016        461785       2268176       2729961
55            Cyprus  2017        457850       2488611       2946461
56            Cyprus  2018        511418       2665743       3177161
57            Cyprus  2019        553613       2689344       3242957
58            Cyprus  2020        572196        532322       1104518
59            Cyprus  2021        713176       1404355       2117531
60            Cyprus  2022        648129       2174270       2822399
61            Cyprus  2023        628284       2537250       3165534
62            Cyprus  2024        686132       3030161       3716293
63           Czechia  2014       7491191       8095885      15587076
64           Czechia  2015       8488637       8706913      17195550
65           Czechia  2016       9067413       9321440      18388853
66           Czechia  2017       9840093      10160468      20000561
67           Czechia  2018      10635756      10611394      21247150
68           Czechia  2019      11107866      10890500      21998366
69           Czechia  2020       8052274       2784170      10836444
70           Czechia  2021       8813943       2569658      11383601
71           Czechia  2022      12080764       7343400      19424164
72           Czechia  2023      12418741       9558930      21977671
73           Czechia  2024      12332067      10477528      22809595
74           Denmark  2014       4243014       2465447       6708461
75           Denmark  2015       4533666       2630938       7164604
76           Denmark  2016       4751127       2767651       7518778
77           Denmark  2017       4801615       2871593       7673208
78           Denmark  2018       4935224       3031450       7966674
79           Denmark  2019       5192979       3086408       8279387
80           Denmark  2020       4129801        906032       5035833
81           Denmark  2021       5232372       1185156       6417528
82           Denmark  2022       6207441       3010487       9217928
83           Denmark  2023       6091016       3319653       9410669
84           Denmark  2024       6043769       3627423       9671192
85           Estonia  2014       1103755       1983315       3087070
86           Estonia  2015       1182979       1929164       3112143
87           Estonia  2016       1268388       2056526       3324914
88           Estonia  2017       1388785       2156147       3544932
89           Estonia  2018       1450960       2140535       3591495
90           Estonia  2019       1536526       2253429       3789955
91           Estonia  2020       1296065        676066       1972131
92           Estonia  2021       1575563        562783       2138346
93           Estonia  2022       1785939       1466959       3252898
94           Estonia  2023       1755905       1669825       3425730
95           Estonia  2024       1755327       1855063       3610390
96           Finland  2014       7928850       2731256      10660106
97           Finland  2015       8112802       2622039      10734841
98           Finland  2016       8319180       2788903      11108083
99           Finland  2017       8614140       3180254      11794394
100          Finland  2018       8742953       3224164      11967117
101          Finland  2019       9136439       3290238      12426677
102          Finland  2020       6446523        895577       7342100
103          Finland  2021       8167713        806962       8974675
104          Finland  2022       9405548       2127475      11533023
105          Finland  2023       9694934       2560523      12255457
106          Finland  2024       9550111       2903960      12454071
107           France  2014     106884663      46073942     152958605
108           France  2015     110695233      46797708     157492941
109           France  2016     112304511      44958968     157263479
110           France  2017     117911260      48919374     166830634
111           France  2018     118970003      52505891     171475894
112           France  2019     123048025      51580030     174628055
113           France  2020      76346861      15542906      91889767
114           France  2021      97081163      20361179     117442342
115           France  2022     122713921      46221455     168935376
116           France  2023     127317904      53412105     180730009
117           France  2024     126508114      54591535     181099649
118          Germany  2014     122068364      32859540     154927904
119          Germany  2015     126062735      34831012     160893747
120          Germany  2016     130218849      35404924     165623773
121          Germany  2017     135004792      37307331     172312123
122          Germany  2018     140494471      38747698     179242169
123          Germany  2019     145679435      39441607     185121042
124          Germany  2020      82691873      12410850      95102723
125          Germany  2021      82122347      11652076      93774423
126          Germany  2022     130157063      28382919     158539982
127          Germany  2023     143495379      34711761     178207140
128          Germany  2024     147267602      37419799     184687401
129           Greece  2014       7414809      15259242      22674051
130           Greece  2015       7665265      16501709      24166974
131           Greece  2016       8080042      16915996      24996038
132           Greece  2017       8142571      19068697      27211268
133           Greece  2018       9264746      24320893      33585639
134           Greece  2019       9163555      25038498      34202053
135           Greece  2020       4617211       5487025      10104236
136           Greece  2021       5652556      12362791      18015347
137           Greece  2022       8311888      23101468      31413356
138           Greece  2023       9505853      26276571      35782424
139           Greece  2024       9776628      27376639      37153267
140          Hungary  2014       5515165       4617751      10132916
141          Hungary  2015       5984739       4928511      10913250
142          Hungary  2016       6346301       5301843      11648144
143          Hungary  2017       6809296       5650077      12459373
144          Hungary  2018       7170933       5945123      13116056
145          Hungary  2019       7285514       6168576      13454090
146          Hungary  2020       4264303       1366412       5630715
147          Hungary  2021       4697535       1868335       6565870
148          Hungary  2022       6805889       4481310      11287199
149          Hungary  2023       6715790       5487087      12202877
150          Hungary  2024       7014437       6113954      13128391
151          Iceland  2014        699733       2596740       3296473
152          Iceland  2015        602016       3376068       3978084
153          Iceland  2016        646790       3977547       4624337
154          Iceland  2019        698737       4533098       5231835
155          Iceland  2020        890363       1040869       1931232
156          Iceland  2021       1190857       1903026       3093883
157          Iceland  2022       1253448       4076435       5329883
158          Iceland  2023       1273185       4815055       6088240
159          Ireland  2014       8120439       2242815      10363254
160          Ireland  2015       8088800       2666848      10755648
161          Ireland  2016       7382650       3172440      10555090
162          Ireland  2018       8970717       3289489      12260206
163          Ireland  2019       8640699       3277804      11918503
164          Ireland  2020       4118000        706004       4824004
165          Ireland  2021       3100000        738622       3838622
166          Ireland  2022       7256000       2668012       9924012
167          Ireland  2023       7452009       3835670      11287679
168          Ireland  2024       8459000       4203374      12662374
169            Italy  2014      54916852      51635500     106552352
170            Italy  2015      58352886      55039251     113392137
171            Italy  2016      60180004      56764239     116944243
172            Italy  2017      62672366      60523190     123195556
173            Italy  2018      64905729      63195203     128100932
174            Italy  2019      66371433      65010220     131381653
175            Italy  2020      39190227      16511911      55702138
176            Italy  2021      51767750      26903217      78670967
177            Italy  2022      63427781      55086852     118514633
178            Italy  2023      65758654      67878055     133636709
179            Italy  2024      65696652      73951291     139647943
180           Latvia  2014        667343       1431038       2098381
181           Latvia  2015        664628       1474765       2139393
182           Latvia  2016        730011       1573632       2303643
183           Latvia  2017        798365       1778973       2577338
184           Latvia  2018        883411       1925397       2808808
185           Latvia  2019        907414       1945919       2853333
186           Latvia  2020        747990        714975       1462965
187           Latvia  2021        864400        442188       1306588
188           Latvia  2022       1033196       1138873       2172069
189           Latvia  2023       1046823       1388972       2435795
190           Latvia  2024       1113409       1587158       2700567
191    Liechtenstein  2014          1054         61251         62305
192    Liechtenstein  2015           983         56666         57649
193    Liechtenstein  2016          1670         69084         70754
194    Liechtenstein  2017          1677         79262         80939
195    Liechtenstein  2018          1781         85283         87064
196    Liechtenstein  2019          1781         98110         99891
197    Liechtenstein  2020          1332         58359         59691
198    Liechtenstein  2021          2638         70764         73402
199    Liechtenstein  2022          1699        100814        102513
200    Liechtenstein  2023          2360        114399        116759
201    Liechtenstein  2024          2798        117789        120587
202        Lithuania  2014       1316696       1356835       2673531
203        Lithuania  2015       1417321       1388487       2805808
204        Lithuania  2016       1546624       1517890       3064514
205        Lithuania  2017       1669403       1583801       3253204
206        Lithuania  2018       1875657       1744733       3620390
207        Lithuania  2019       2099777       1937972       4037749
208        Lithuania  2020       1615148        511566       2126714
209        Lithuania  2021       1962633        505361       2467994
210        Lithuania  2022       2675666       1149537       3825203
211        Lithuania  2023       2622501       1369549       3992050
212        Lithuania  2024       2656513       1449052       4105565
213       Luxembourg  2014        104417       1038475       1142892
214       Luxembourg  2015        113471       1150913       1264384
215       Luxembourg  2016        116915       1166258       1283173
216       Luxembourg  2017        131482       1159497       1290979
217       Luxembourg  2018        135711       1141038       1276749
218       Luxembourg  2019        139289       1186374       1325663
219       Luxembourg  2020        151783        473388        625171
220       Luxembourg  2021        153785        683259        837044
221       Luxembourg  2022        181576       1132054       1313630
222       Luxembourg  2023        183963       1258072       1442035
223       Luxembourg  2024        203446       1364853       1568299
224            Malta  2014        155378       1399301       1554679
225            Malta  2015        157267       1428801       1586068
226            Malta  2016        151389       1468143       1619532
227            Malta  2017        167109       1662358       1829467
228            Malta  2018        184577       1798002       1982579
229            Malta  2019        201076       1821836       2022912
230            Malta  2020        219321        486393        705714
231            Malta  2021        245245        736742        981987
232            Malta  2022        254512       1559649       1814161
233            Malta  2023        259363       1992637       2252000
234            Malta  2024        271588       2278803       2550391
235       Montenegro  2015        153185       1559924       1713109
236       Montenegro  2016        151696       1662121       1813817
237       Montenegro  2017        111890        843609        955499
238       Montenegro  2022        140333       1025642       1165975
239       Montenegro  2023        158021       1278125       1436146
240       Montenegro  2024        167140       1279340       1446480
241      Netherlands  2014      21931193      13924881      35856074
242      Netherlands  2015      22311303      15007135      37318438
243      Netherlands  2016      23053578      15829488      38883066
244      Netherlands  2017      24310943      17924191      42235134
245      Netherlands  2018      25132289      18780326      43912615
246      Netherlands  2019      25786602      20129400      45916002
247      Netherlands  2020      20035412       7265370      27300782
248      Netherlands  2021      25472295       6248089      31720384
249      Netherlands  2022      29417995      16582261      46000256
250      Netherlands  2023      29100201      20303590      49403791
251      Netherlands  2024      30012347      21253245      51265592
252  North Macedonia  2014        207572        417090        624662
253  North Macedonia  2015        219532        479152        698684
254  North Macedonia  2016        228882        508300        737182
255  North Macedonia  2017        242674        626879        869553
256  North Macedonia  2018        268612        702833        971445
257  North Macedonia  2019        276091        755438       1031529
258  North Macedonia  2020        233969        118101        352070
259  North Macedonia  2021        251830        293919        545749
260  North Macedonia  2022        261898        537037        798935
261  North Macedonia  2023        266035        733441        999476
262  North Macedonia  2024        255652        829599       1085251
263           Norway  2014      13824254       4854610      18678864
264           Norway  2015      14029604       5303531      19333135
265           Norway  2016      14673056       5920859      20593915
266           Norway  2020      10034858       1387137      11421995
267           Norway  2021      11149706       1435366      12585072
268           Norway  2022      13133328       4979438      18112766
269           Norway  2023      13353220       5951367      19304587
270           Norway  2024      13492337       6670410      20162747
271           Poland  2014      19613643       5470335      25083978
272           Poland  2015      21252486       5689570      26942056
273           Poland  2016      23729515       6378793      30108308
274           Poland  2017      25185677       6803667      31989344
275           Poland  2018      26813699       7082231      33895930
276           Poland  2019      28197545       7470546      35668091
277           Poland  2020      15615208       2263761      17878969
278           Poland  2021      19689140       2509832      22198972
279           Poland  2022      28402393       5846611      34249004
280           Poland  2023      29164646       7074555      36239201
281           Poland  2024      30966882       7875518      38842400
282         Portugal  2014       8213985       9688312      17902297
283         Portugal  2015       8940270      10839925      19780195
284         Portugal  2016       9572917      12343982      21916899
285         Portugal  2017      10257547      14299650      24557197
286         Portugal  2018      10830619      15035803      25866422
287         Portugal  2019      11694640      16200438      27895078

In [753]:
arrivals_wide.dtypes

country           str
year            int64
arrivals_dom    Int64
arrivals_for    Int64
arrivals_tot    Int64
dtype: object

In [754]:
# Carica file
nights = pd.read_csv("../res/tin00175_linear.csv")

In [755]:
nights

,DATAFLOW,LAST UPDATE,freq,c_resid,unit,nace_r2,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:TIN00175(1.0),28/05/26 11:00:00,Annual,Domestic country,Number,Hotels; holiday and other short-stay accommoda...,Albania,2018,931190,e,NaN
1,ESTAT:TIN00175(1.0),28/05/26 11:00:00,Annual,Domestic country,Number,Hotels; holiday and other short-stay accommoda...,Albania,2019,1103905,e,NaN
2,ESTAT:TIN00175(1.0),28/05/26 11:00:00,Annual,Domestic country,Number,Hotels; holiday and other short-stay accommoda...,Albania,2020,800028,e,NaN
3,ESTAT:TIN00175(1.0),28/05/26 11:00:00,Annual,Domestic country,Number,Hotels; holiday and other short-stay accommoda...,Albania,2021,1155185,e,NaN
4,ESTAT:TIN00175(1.0),28/05/26 11:00:00,Annual,Domestic country,Number,Hotels; holiday and other short-stay accommoda...,Albania,2022,1339177,e,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1156,ESTAT:TIN00175(1.0),28/05/26 11:00:00,Annual,Total,Number,Hotels; holiday and other short-stay accommoda...,Türkiye,2023,203187830,NaN,NaN
1157,ESTAT:TIN00175(1.0),28/05/26 11:00:00,Annual,Total,Number,Hotels; holiday and other short-stay accommoda...,Türkiye,2024,216017715,NaN,NaN
1158,ESTAT:TIN00175(1.0),28/05/26 11:00:00,Annual,Total,Number,Hotels; holiday and other short-stay accommoda...,United Kingdom,2014,443380180,NaN,NaN
1159,ESTAT:TIN00175(1.0),28/05/26 11:00:00,Annual,Total,Number,Hotels; holiday and other short-stay accommoda...,United Kingdom,2015,465438028,NaN,NaN
1160,ESTAT:TIN00175(1.0),28/05/26 11:00:00,Annual,Total,Number,Hotels; holiday and other short-stay accommoda...,United Kingdom,2016,476356101,NaN,NaN

In [756]:
# Tieni solo le colonne utili
nights = nights[["geo", "TIME_PERIOD", "c_resid", "OBS_VALUE"]]

# Rinomina
nights = nights.rename(columns={
    "geo": "country",
    "TIME_PERIOD": "year",
    "c_resid": "resid",
    "OBS_VALUE": "nights"
})

# Ordina
nights = nights.sort_values(
    by=["resid", "country", "year"]
).reset_index(drop=True)

In [757]:
print(nights.to_string())

                                        country  year             resid      nights
0                                       Albania  2018  Domestic country      931190
1                                       Albania  2019  Domestic country     1103905
2                                       Albania  2020  Domestic country      800028
3                                       Albania  2021  Domestic country     1155185
4                                       Albania  2022  Domestic country     1339177
5                                       Albania  2023  Domestic country     2101259
6                                       Albania  2024  Domestic country     2214777
7                                       Austria  2014  Domestic country    32341680
8                                       Austria  2015  Domestic country    33060945
9                                       Austria  2016  Domestic country    34558881
10                                      Austria  2017  Domestic country    35082222
11                                      Austria  2018  Domestic country    35935386
12                                      Austria  2019  Domestic country    36504339
13                                      Austria  2020  Domestic country    27990963
14                                      Austria  2021  Domestic country    26674565
15                                      Austria  2022  Domestic country    35592486
16                                      Austria  2023  Domestic country    36742409
17                                      Austria  2024  Domestic country    37192120
18                                      Austria  2025  Domestic country    37437110
19                                      Belgium  2014  Domestic country    15536809
20                                      Belgium  2015  Domestic country    19528328
21                                      Belgium  2016  Domestic country    19792020
22                                      Belgium  2017  Domestic country    20020465
23                                      Belgium  2018  Domestic country    20755601
24                                      Belgium  2019  Domestic country    21308009
25                                      Belgium  2020  Domestic country    13630700
26                                      Belgium  2021  Domestic country    21369885
27                                      Belgium  2022  Domestic country    23646343
28                                      Belgium  2023  Domestic country    23102177
29                                      Belgium  2024  Domestic country    22563809
30                                     Bulgaria  2014  Domestic country     7620593
31                                     Bulgaria  2015  Domestic country     8045535
32                                     Bulgaria  2016  Domestic country     9035330
33                                     Bulgaria  2017  Domestic country     8948529
34                                     Bulgaria  2018  Domestic country     9096088
35                                     Bulgaria  2019  Domestic country     9674945
36                                     Bulgaria  2020  Domestic country     7312194
37                                     Bulgaria  2021  Domestic country     9626501
38                                     Bulgaria  2022  Domestic country    11286336
39                                     Bulgaria  2023  Domestic country    12311004
40                                     Bulgaria  2024  Domestic country    12588156
41                                      Croatia  2014  Domestic country     5052330
42                                      Croatia  2015  Domestic country     5655990
43                                      Croatia  2016  Domestic country     5759532
44                                      Croatia  2017  Domestic country     5918043
45                                      Croatia  2018  Domestic country     6427780
46                                      Croatia  2019  Domestic country     7053932
47                                      Croatia  2020  Domestic country     5394858
48                                      Croatia  2021  Domestic country     7327520
49                                      Croatia  2022  Domestic country     7726655
50                                      Croatia  2023  Domestic country     8083165
51                                      Croatia  2024  Domestic country     8688362
52                                       Cyprus  2014  Domestic country      830943
53                                       Cyprus  2015  Domestic country      824517
54                                       Cyprus  2016  Domestic country      844182
55                                       Cyprus  2017  Domestic country      834104
56                                       Cyprus  2018  Domestic country      916840
57                                       Cyprus  2019  Domestic country     1012569
58                                       Cyprus  2020  Domestic country     1092094
59                                       Cyprus  2021  Domestic country     1547845
60                                       Cyprus  2022  Domestic country     1317451
61                                       Cyprus  2023  Domestic country     1207788
62                                       Cyprus  2024  Domestic country     1350625
63                                      Czechia  2014  Domestic country    20836817
64                                      Czechia  2015  Domestic country    23807391
65                                      Czechia  2016  Domestic country    25428808
66                                      Czechia  2017  Domestic country    26962382
67                                      Czechia  2018  Domestic country    28753901
68                                      Czechia  2019  Domestic country    29844204
69                                      Czechia  2020  Domestic country    23994436
70                                      Czechia  2021  Domestic country    25376927
71                                      Czechia  2022  Domestic country    32459645
72                                      Czechia  2023  Domestic country    32480862
73                                      Czechia  2024  Domestic country    31761973
74                                      Denmark  2014  Domestic country    19038780
75                                      Denmark  2015  Domestic country    19637924
76                                      Denmark  2016  Domestic country    20266251
77                                      Denmark  2017  Domestic country    20243007
78                                      Denmark  2018  Domestic country    20685784
79                                      Denmark  2019  Domestic country    21349055
80                                      Denmark  2020  Domestic country    18890042
81                                      Denmark  2021  Domestic country    22735819
82                                      Denmark  2022  Domestic country    25017892
83                                      Denmark  2023  Domestic country    24268566
84                                      Denmark  2024  Domestic country    24010206
85                                      Estonia  2014  Domestic country     1890165
86                                      Estonia  2015  Domestic country     2011663
87                                      Estonia  2016  Domestic country     2213547
88                                      Estonia  2017  Domestic country     2358880
89                                      Estonia  2018  Domestic country     2455763
90                                      Estonia  2019  Domestic country     2591410
91                                      Estonia  2020  Domestic country     2270210
92                                      Estonia  2021  Domestic country     2716254
93                                      Estonia  2022  Domestic country     3031814
94                                      Estonia  2023  Domestic country     3003818
95                                      Estonia  2024  Domestic country     2977933
96    European Union - 27 countries (from 2020)  2014  Domestic country  1278406482
97    European Union - 27 countries (from 2020)  2015  Domestic country  1332621050
98    European Union - 27 countries (from 2020)  2016  Domestic country  1373271744
99    European Union - 27 countries (from 2020)  2017  Domestic country  1426601419
100   European Union - 27 countries (from 2020)  2018  Domestic country  1467002532
101   European Union - 27 countries (from 2020)  2019  Domestic country  1514855699
102   European Union - 27 countries (from 2020)  2020  Domestic country  1009515644
103   European Union - 27 countries (from 2020)  2021  Domestic country  1245706618
104   European Union - 27 countries (from 2020)  2022  Domestic country  1543617046
105   European Union - 27 countries (from 2020)  2023  Domestic country  1566636546
106   European Union - 27 countries (from 2020)  2024  Domestic country  1569725908
107                                     Finland  2014  Domestic country    14075320
108                                     Finland  2015  Domestic country    14227773
109                                     Finland  2016  Domestic country    14572158
110                                     Finland  2017  Domestic country    15171320
111                                     Finland  2018  Domestic country    15392495
112                                     Finland  2019  Domestic country    16039663
113                                     Finland  2020  Domestic country    12032325
114                                     Finland  2021  Domestic country    15403349
115                                     Finland  2022  Domestic country    16996271
116                                     Finland  2023  Domestic country    17080229
117                                     Finland  2024  Domestic country    16309732
118                                      France  2014  Domestic country   271406467
119                                      France  2015  Domestic country   279587890
120                                      France  2016  Domestic country   280850016
121                                      France  2017  Domestic country   299558737
122                                      France  2018  Domestic country   302038667
123                                      France  2019  Domestic country   310563771
124                                      France  2020  Domestic country   212781655
125                                      France  2021  Domestic country   267865936
126                                      France  2022  Domestic country   324342680
127                                      France  2023  Domestic country   321903813
128                                      France  2024  Domestic country   317036065
129                                     Germany  2014  Domestic country   291722145
130                                     Germany  2015  Domestic country   299220311
131                                     Germany  2016  Domestic country   308904957
132                                     Germany  2017  Domestic country   318051999
133                                     Germany  2018  Domestic country   332594428
134                                     Germany  2019  Domestic country   347694001
135                                     Germany  2020  Domestic country   229025364
136                                     Germany  2021  Domestic country   235371154
137                                     Germany  2022  Domestic country   332792753
138                                     Germany  2023  Domestic country   351060606
139                                     Germany  2024  Domestic country   354827032
140                                      Greece  2014  Domestic country    20589198
141                                      Greece  2015  Domestic country    20900203
142                                      Greece  2016  Domestic country    22107192
143                                      Greece  2017  Domestic country    21974593
144                                      Greece  2018  Domestic country    24064088
145                                      Greece  2019  Domestic country    23623077
146                                      Greece  2020  Domestic country    12277230
147                                      Greece  2021  Domestic country    14963208
148                                      Greece  2022  Domestic country    21195814
149                                      Greece  2023  Domestic country    24103015
150                                      Greece  2024  Domestic country    24764341
151                                     Hungary  2014  Domestic country    13702543
152                                     Hungary  2015  Domestic country    14580503
153                                     Hungary  2016  Domestic country    15489123
154                                     Hungary  2017  Domestic country    16666938
155                                     Hungary  2018  Domestic country    17489671
156                                     Hungary  2019  Domestic country    17447388
157                                     Hungary  2020  Domestic country    10825115
158                                     Hungary  2021  Domestic country    12299937
159                                     Hungary  2022  Domestic country    17081903
160                                     Hungary  2023  Domestic country    16314547
161                                     Hungary  2024  Domestic country    16578557
162                                     Iceland  2014  Domestic country     1085049
163                                     Iceland  2015  Domestic country      930643
164                                     Iceland  2016  Domestic country     1044289
165                                     Iceland  2019  Domestic country     1089677
166                                     Iceland  2020  Domestic country     1467548
167                                     Iceland  2021  Domestic country     1939623
168                                     Iceland  2022  Domestic country     1968404
169                                     Iceland  2023  Domestic country     1961430
170                                     Ireland  2014  Domestic country    17889958
171                                     Ireland  2015  Domestic country    16247706
172                                     Ireland  2016  Domestic country    14915287
173                                     Ireland  2018  Domestic country    18257838
174                                     Ireland  2019  Domestic country    16295535
175                                     Ireland  2020  Domestic country    11624000
176                                     Ireland  2021  Domestic country     9696000
177                                     Ireland  2022  Domestic country    18456000
178                                     Ireland  2023  Domestic country    16274003
179                                     Ireland  2024  Domestic country    17327991
180                                       Italy  2014  Domestic country   190978299
181                                       Italy  2015  Domestic country   200249044
182                                       Italy  2016  Domestic country   203540299
183                                       Italy  2017  Domestic country   209970369
184                                       Italy  2018  Domestic country   212334391
185                                       Italy  2019  Domestic country   216076587
186                                       Italy  2020  Domestic country   143003478
187                                       Italy  2021  Domestic country   183054967
188                                       Italy  2022  Domestic country   210939098
189                                       Italy  2023  Domestic country   212987794
190                                       Italy  2024  Domestic country   212209602
191                                      Latvia  2014  Domestic country     1282484
192                                      Latvia  2015  Domestic country     1236025
193                                      Latvia  2016  Domestic country     1372065
194                                      Latvia  2017  Domestic country     1544402
195                                      Latvia  2018  Domestic country     1625773
196                                      Latvia  2019  Domestic country     1658379
197                                      Latvia  2020  Domestic country     1385037
198                                      Latvia  2021  Domestic country     1516390
199                                      Latvia  2022  Domestic country     1769701
200                                      Latvia  2023  Domestic country     1793070
201                                      Latvia  2024  Domestic country     1850960
202                               Liechtenstein  2014  Domestic country        2070
203                               Liechtenstein  2015  Domestic country        2019
204                               Liechtenstein  2016  Domestic country        3069
205                               Liechtenstein  2017  Domestic country        3732
206                               Liechtenstein  2018  Domestic country        3433
207                               Liechtenstein  2019  Domestic country        3491
208                               Liechtenstein  2020  Domestic country        3337
209                               Liechtenstein  2021  Domestic country        6084
210                               Liechtenstein  2022  Domestic country        3707
211                               Liechtenstein  2023  Domestic country        4525
212                               Liechtenstein  2024  Domestic country        5277
213                                   Lithuania  2014  Domestic country     3431178
214                                   Lithuania  2015  Domestic country     3570465
215                                   Lithuania  2016  Domestic country     3719254
216                                   Lithuania  2017  Domestic country     3933691
217                                   Lithuania  2018  Domestic country     4354797
218                                   Lithuania  2019  Domestic country     4804232
219                                   Lithuania  2020  Domestic country     3812166
220                                   Lithuania  2021  Domestic country     4359753
221                                   Lithuania  2022  Domestic country     5458686
222                                   Lithuania  2023  Domestic country     5471881
223                                   Lithuania  2024  Domestic country     5537953
224                                  Luxembourg  2014  Domestic country      354226
225                                  Luxembourg  2015  Domestic country      340447
226                                  Luxembourg  2016  Domestic country      332673
227                                  Luxembourg  2017  Domestic country      358649
228                                  Luxembourg  2018  Domestic country      371120
229                                  Luxembourg  2019  Domestic country      367594
230                                  Luxembourg  2020  Domestic country      403414
231                                  Luxembourg  2021  Domestic country      434995
232                                  Luxembourg  2022  Domestic country      488592
233                                  Luxembourg  2023  Domestic country      473681
234                                  Luxembourg  2024  Domestic country      458952
235                                       Malta  2014  Domestic country      352733
236                                       Malta  2015  Domestic country      373242

In [758]:
# Elimina aggregato UE
nights = nights[
    nights["country"] != "European Union - 27 countries (from 2020)"
].reset_index(drop=True)

In [759]:
print(nights.to_string())

              country  year             resid     nights
0             Albania  2018  Domestic country     931190
1             Albania  2019  Domestic country    1103905
2             Albania  2020  Domestic country     800028
3             Albania  2021  Domestic country    1155185
4             Albania  2022  Domestic country    1339177
5             Albania  2023  Domestic country    2101259
6             Albania  2024  Domestic country    2214777
7             Austria  2014  Domestic country   32341680
8             Austria  2015  Domestic country   33060945
9             Austria  2016  Domestic country   34558881
10            Austria  2017  Domestic country   35082222
11            Austria  2018  Domestic country   35935386
12            Austria  2019  Domestic country   36504339
13            Austria  2020  Domestic country   27990963
14            Austria  2021  Domestic country   26674565
15            Austria  2022  Domestic country   35592486
16            Austria  2023  Domestic country   36742409
17            Austria  2024  Domestic country   37192120
18            Austria  2025  Domestic country   37437110
19            Belgium  2014  Domestic country   15536809
20            Belgium  2015  Domestic country   19528328
21            Belgium  2016  Domestic country   19792020
22            Belgium  2017  Domestic country   20020465
23            Belgium  2018  Domestic country   20755601
24            Belgium  2019  Domestic country   21308009
25            Belgium  2020  Domestic country   13630700
26            Belgium  2021  Domestic country   21369885
27            Belgium  2022  Domestic country   23646343
28            Belgium  2023  Domestic country   23102177
29            Belgium  2024  Domestic country   22563809
30           Bulgaria  2014  Domestic country    7620593
31           Bulgaria  2015  Domestic country    8045535
32           Bulgaria  2016  Domestic country    9035330
33           Bulgaria  2017  Domestic country    8948529
34           Bulgaria  2018  Domestic country    9096088
35           Bulgaria  2019  Domestic country    9674945
36           Bulgaria  2020  Domestic country    7312194
37           Bulgaria  2021  Domestic country    9626501
38           Bulgaria  2022  Domestic country   11286336
39           Bulgaria  2023  Domestic country   12311004
40           Bulgaria  2024  Domestic country   12588156
41            Croatia  2014  Domestic country    5052330
42            Croatia  2015  Domestic country    5655990
43            Croatia  2016  Domestic country    5759532
44            Croatia  2017  Domestic country    5918043
45            Croatia  2018  Domestic country    6427780
46            Croatia  2019  Domestic country    7053932
47            Croatia  2020  Domestic country    5394858
48            Croatia  2021  Domestic country    7327520
49            Croatia  2022  Domestic country    7726655
50            Croatia  2023  Domestic country    8083165
51            Croatia  2024  Domestic country    8688362
52             Cyprus  2014  Domestic country     830943
53             Cyprus  2015  Domestic country     824517
54             Cyprus  2016  Domestic country     844182
55             Cyprus  2017  Domestic country     834104
56             Cyprus  2018  Domestic country     916840
57             Cyprus  2019  Domestic country    1012569
58             Cyprus  2020  Domestic country    1092094
59             Cyprus  2021  Domestic country    1547845
60             Cyprus  2022  Domestic country    1317451
61             Cyprus  2023  Domestic country    1207788
62             Cyprus  2024  Domestic country    1350625
63            Czechia  2014  Domestic country   20836817
64            Czechia  2015  Domestic country   23807391
65            Czechia  2016  Domestic country   25428808
66            Czechia  2017  Domestic country   26962382
67            Czechia  2018  Domestic country   28753901
68            Czechia  2019  Domestic country   29844204
69            Czechia  2020  Domestic country   23994436
70            Czechia  2021  Domestic country   25376927
71            Czechia  2022  Domestic country   32459645
72            Czechia  2023  Domestic country   32480862
73            Czechia  2024  Domestic country   31761973
74            Denmark  2014  Domestic country   19038780
75            Denmark  2015  Domestic country   19637924
76            Denmark  2016  Domestic country   20266251
77            Denmark  2017  Domestic country   20243007
78            Denmark  2018  Domestic country   20685784
79            Denmark  2019  Domestic country   21349055
80            Denmark  2020  Domestic country   18890042
81            Denmark  2021  Domestic country   22735819
82            Denmark  2022  Domestic country   25017892
83            Denmark  2023  Domestic country   24268566
84            Denmark  2024  Domestic country   24010206
85            Estonia  2014  Domestic country    1890165
86            Estonia  2015  Domestic country    2011663
87            Estonia  2016  Domestic country    2213547
88            Estonia  2017  Domestic country    2358880
89            Estonia  2018  Domestic country    2455763
90            Estonia  2019  Domestic country    2591410
91            Estonia  2020  Domestic country    2270210
92            Estonia  2021  Domestic country    2716254
93            Estonia  2022  Domestic country    3031814
94            Estonia  2023  Domestic country    3003818
95            Estonia  2024  Domestic country    2977933
96            Finland  2014  Domestic country   14075320
97            Finland  2015  Domestic country   14227773
98            Finland  2016  Domestic country   14572158
99            Finland  2017  Domestic country   15171320
100           Finland  2018  Domestic country   15392495
101           Finland  2019  Domestic country   16039663
102           Finland  2020  Domestic country   12032325
103           Finland  2021  Domestic country   15403349
104           Finland  2022  Domestic country   16996271
105           Finland  2023  Domestic country   17080229
106           Finland  2024  Domestic country   16309732
107            France  2014  Domestic country  271406467
108            France  2015  Domestic country  279587890
109            France  2016  Domestic country  280850016
110            France  2017  Domestic country  299558737
111            France  2018  Domestic country  302038667
112            France  2019  Domestic country  310563771
113            France  2020  Domestic country  212781655
114            France  2021  Domestic country  267865936
115            France  2022  Domestic country  324342680
116            France  2023  Domestic country  321903813
117            France  2024  Domestic country  317036065
118           Germany  2014  Domestic country  291722145
119           Germany  2015  Domestic country  299220311
120           Germany  2016  Domestic country  308904957
121           Germany  2017  Domestic country  318051999
122           Germany  2018  Domestic country  332594428
123           Germany  2019  Domestic country  347694001
124           Germany  2020  Domestic country  229025364
125           Germany  2021  Domestic country  235371154
126           Germany  2022  Domestic country  332792753
127           Germany  2023  Domestic country  351060606
128           Germany  2024  Domestic country  354827032
129            Greece  2014  Domestic country   20589198
130            Greece  2015  Domestic country   20900203
131            Greece  2016  Domestic country   22107192
132            Greece  2017  Domestic country   21974593
133            Greece  2018  Domestic country   24064088
134            Greece  2019  Domestic country   23623077
135            Greece  2020  Domestic country   12277230
136            Greece  2021  Domestic country   14963208
137            Greece  2022  Domestic country   21195814
138            Greece  2023  Domestic country   24103015
139            Greece  2024  Domestic country   24764341
140           Hungary  2014  Domestic country   13702543
141           Hungary  2015  Domestic country   14580503
142           Hungary  2016  Domestic country   15489123
143           Hungary  2017  Domestic country   16666938
144           Hungary  2018  Domestic country   17489671
145           Hungary  2019  Domestic country   17447388
146           Hungary  2020  Domestic country   10825115
147           Hungary  2021  Domestic country   12299937
148           Hungary  2022  Domestic country   17081903
149           Hungary  2023  Domestic country   16314547
150           Hungary  2024  Domestic country   16578557
151           Iceland  2014  Domestic country    1085049
152           Iceland  2015  Domestic country     930643
153           Iceland  2016  Domestic country    1044289
154           Iceland  2019  Domestic country    1089677
155           Iceland  2020  Domestic country    1467548
156           Iceland  2021  Domestic country    1939623
157           Iceland  2022  Domestic country    1968404
158           Iceland  2023  Domestic country    1961430
159           Ireland  2014  Domestic country   17889958
160           Ireland  2015  Domestic country   16247706
161           Ireland  2016  Domestic country   14915287
162           Ireland  2018  Domestic country   18257838
163           Ireland  2019  Domestic country   16295535
164           Ireland  2020  Domestic country   11624000
165           Ireland  2021  Domestic country    9696000
166           Ireland  2022  Domestic country   18456000
167           Ireland  2023  Domestic country   16274003
168           Ireland  2024  Domestic country   17327991
169             Italy  2014  Domestic country  190978299
170             Italy  2015  Domestic country  200249044
171             Italy  2016  Domestic country  203540299
172             Italy  2017  Domestic country  209970369
173             Italy  2018  Domestic country  212334391
174             Italy  2019  Domestic country  216076587
175             Italy  2020  Domestic country  143003478
176             Italy  2021  Domestic country  183054967
177             Italy  2022  Domestic country  210939098
178             Italy  2023  Domestic country  212987794
179             Italy  2024  Domestic country  212209602
180            Latvia  2014  Domestic country    1282484
181            Latvia  2015  Domestic country    1236025
182            Latvia  2016  Domestic country    1372065
183            Latvia  2017  Domestic country    1544402
184            Latvia  2018  Domestic country    1625773
185            Latvia  2019  Domestic country    1658379
186            Latvia  2020  Domestic country    1385037
187            Latvia  2021  Domestic country    1516390
188            Latvia  2022  Domestic country    1769701
189            Latvia  2023  Domestic country    1793070
190            Latvia  2024  Domestic country    1850960
191     Liechtenstein  2014  Domestic country       2070
192     Liechtenstein  2015  Domestic country       2019
193     Liechtenstein  2016  Domestic country       3069
194     Liechtenstein  2017  Domestic country       3732
195     Liechtenstein  2018  Domestic country       3433
196     Liechtenstein  2019  Domestic country       3491
197     Liechtenstein  2020  Domestic country       3337
198     Liechtenstein  2021  Domestic country       6084
199     Liechtenstein  2022  Domestic country       3707
200     Liechtenstein  2023  Domestic country       4525
201     Liechtenstein  2024  Domestic country       5277
202         Lithuania  2014  Domestic country    3431178
203         Lithuania  2015  Domestic country    3570465
204         Lithuania  2016  Domestic country    3719254
205         Lithuania  2017  Domestic country    3933691
206         Lithuania  2018  Domestic country    4354797
207         Lithuania  2019  Domestic country    4804232
208         Lithuania  2020  Domestic country    3812166
209         Lithuania  2021  Domestic country    4359753
210         Lithuania  2022  Domestic country    5458686
211         Lithuania  2023  Domestic country    5471881
212         Lithuania  2024  Domestic country    5537953
213        Luxembourg  2014  Domestic country     354226
214        Luxembourg  2015  Domestic country     340447
215        Luxembourg  2016  Domestic country     332673
216        Luxembourg  2017  Domestic country     358649
217        Luxembourg  2018  Domestic country     371120
218        Luxembourg  2019  Domestic country     367594
219        Luxembourg  2020  Domestic country     403414
220        Luxembourg  2021  Domestic country     434995
221        Luxembourg  2022  Domestic country     488592
222        Luxembourg  2023  Domestic country     473681
223        Luxembourg  2024  Domestic country     458952
224             Malta  2014  Domestic country     352733
225             Malta  2015  Domestic country     373242
226             Malta  2016  Domestic country     348753
227             Malta  2017  Domestic country     396167
228             Malta  2018  Domestic country     429040
229             Malta  2019  Domestic country     474950
230             Malta  2020  Domestic country     547501
231             Malta  2021  Domestic country     672357
232             Malta  2022  Domestic country     661199
233             Malta  2023  Domestic country     685459
234             Malta  2024  Domestic country     715096
235        Montenegro  2015  Domestic country     747576
236        Montenegro  2016  Domestic country     721530
237        Montenegro  2017  Domestic country     431370
238        Montenegro  2022  Domestic country     528457
239        Montenegro  2023  Domestic country     564693
240        Montenegro  2024  Domestic country     597156
241       Netherlands  2014  Domestic country   65328010
242       Netherlands  2015  Domestic country   66236714
243       Netherlands  2016  Domestic country   66589317
244       Netherlands  2017  Domestic country   67528773
245       Netherlands  2018  Domestic country   69080031
246       Netherlands  2019  Domestic country   71692192
247       Netherlands  2020  Domestic country   64042422
248       Netherlands  2021  Domestic country   82479471
249       Netherlands  2022  Domestic country   84478125
250       Netherlands  2023  Domestic country   83168429
251       Netherlands  2024  Domestic country   83857504
252   North Macedonia  2014  Domestic country     618865
253   North Macedonia  2015  Domestic country     619060
254   North Macedonia  2016  Domestic country     644167
255   North Macedonia  2017  Domestic country     686100
256   North Macedonia  2018  Domestic country     727607
257   North Macedonia  2019  Domestic country     721216
258   North Macedonia  2020  Domestic country     621922
259   North Macedonia  2021  Domestic country     652150
260   North Macedonia  2022  Domestic country     675621
261   North Macedonia  2023  Domestic country     668340
262   North Macedonia  2024  Domestic country     650132
263            Norway  2014  Domestic country   22162724
264            Norway  2015  Domestic country   22739800
265            Norway  2016  Domestic country   23301585
266            Norway  2020  Domestic country   20402530
267            Norway  2021  Domestic country   23782515
268            Norway  2022  Domestic country   26313965
269            Norway  2023  Domestic country   25907064
270            Norway  2024  Domestic country   26162501
271            Poland  2014  Domestic country   53587348
272            Poland  2015  Domestic country   57476764
273            Poland  2016  Domestic country   63814635
274            Poland  2017  Domestic country   67175700
275            Poland  2018  Domestic country   71117812
276            Poland  2019  Domestic country   74659162
277            Poland  2020  Domestic country   44754216
278            Poland  2021  Domestic country   55672507
279            Poland  2022  Domestic country   75194553
280            Poland  2023  Domestic country   75786956
281            Poland  2024  Domestic country   79256114
282          Portugal  2014  Domestic country   19349092
283          Portugal  2015  Domestic country   20522609
284          Portugal  2016  Domestic country   22054931
285          Portugal  2017  Domestic country   23150944
286          Portugal  2018  Domestic country   24555272
287          Portugal  2019  Domestic country   26002000
288          Portugal  2020  Domestic country   16775906
289          Portugal  2021  Domestic country   22369511
290          Portugal  2022  Domestic country   27363326
291          Portugal  2023  Domestic country   27939627
292          Portugal  2024  Domestic country   28416210
293           Romania  2014  Domestic country   16467780
294           Romania  2015  Domestic country   18985269
295           Romania  2016  Domestic country   20462599
296           Romania  2017  Domestic country   21647603
297           Romania  2018  Domestic country   23154660
298           Romania  2019  Domestic country   24620841
299           Romania  2020  Domestic country   13458330
300           Romania  2021  Domestic country   20508623
301           Romania  2022  Domestic country   22976069
302           Romania  2023  Domestic country   24738466
303           Romania  2024  Domestic country   25290103
304            Serbia  2014  Domestic country    3879642
305            Serbia  2015  Domestic country    4217374
306            Serbia  2016  Domestic country    4766970
307            Serbia  2020  Domestic country    4933011
308            Serbia  2021  Domestic country    5727351
309            Serbia  2022  Domestic country    7306219
310            Serbia  2023  Domestic country    6858331
311            Serbia  2024  Domestic country    6564402
312          Slovakia  2014  Domestic country    6928868
313          Slovakia  2015  Domestic country    7791475
314          Slovakia  2016  Domestic country    8856568
315          Slovakia  2017  Domestic country    9350992
316          Slovakia  2018  Domestic country    9629258
317          Slovakia  2019  Domestic country   11177659
318          Slovakia  2020  Domestic country    7194393
319          Slovakia  2021  Domestic country    6491559
320          Slovakia  2022  Domestic country    8697709
321          Slovakia  2023  Domestic country    9639648
322          Slovakia  2024  Domestic country    9769022
323          Slovenia  2014  Domestic country    3465829
324          Slovenia  2015  Domestic country    3695121
325          Slovenia  2016  Domestic country    3805661
326          Slovenia  2017  Domestic country    3982065
327          Slovenia  2019  Domestic country    4403016
328          Slovenia  2020  Domestic country    5845635
329          Slovenia  2021  Domestic country    6451205
330          Slovenia  2022  Domestic country    5503765
331          Slovenia  2023  Domestic country    4569928
332          Slovenia  2024  Domestic country    4498552
333             Spain  2014  Domestic country  144327228
334             Spain  2015  Domestic country  152808273
335             Spain  2016  Domestic country  160400822
336             Spain  2017  Domestic country  165292267
337             Spain  2018  Domestic country  165918083
338             Spain  2019  Domestic country  170722142
339             Spain  2020  Domestic country   83778193
340             Spain  2021  Domestic country  145188204
341             Spain  2022  Domestic country  180184036
342             Spain  2023  Domestic country  183129528
343             Spain  2024  Domestic country  182936205
344            Sweden  2014  Domestic country   40019659
345            Sweden  2015  Domestic country   41998923
346            Sweden  2016  Domestic country   43236883
347            Sweden  2017  Domestic country   44044499
348            Sweden  2018  Domestic country   45171193

In [760]:
nights.dtypes

country      str
year       int64
resid        str
nights     int64
dtype: object

In [761]:
# Long -> Wide
nights_wide = nights.pivot_table(
    index=["country", "year"],
    columns="resid",
    values="nights",
    aggfunc="sum"
).reset_index()

In [762]:
# Rinomina colonne
nights_wide = nights_wide.rename(columns={
    "Total": "nights_tot",
    "Domestic country": "nights_dom",
    "Foreign country": "nights_for"
})

In [763]:
# Rimuove il nome "resid" sopra le colonne
nights_wide.columns.name = None

nights_wide

            country  year  nights_dom  nights_for  nights_tot
0           Albania  2018      931190     2143467     3074657
1           Albania  2019     1103905     2149514     3253419
2           Albania  2020      800028      805416     1605444
3           Albania  2021     1155185     2030887     3186072
4           Albania  2022     1339177     2492152     3831329
..              ...   ...         ...         ...         ...
371         Türkiye  2023    72595189   130592641   203187830
372         Türkiye  2024    76418208   139599507   216017715
373  United Kingdom  2014   185710000   257670180   443380180
374  United Kingdom  2015   189788000   275650028   465438028
375  United Kingdom  2016   196903030   279453071   476356101

[376 rows x 5 columns]

In [764]:
# Interi
cols = ["nights_tot", "nights_dom", "nights_for"]
nights_wide[cols] = nights_wide[cols].astype("Int64")

In [765]:
# Controlli
print(nights_wide.head())
print(nights_wide.shape)
print(nights_wide.isna().sum())

print(nights_wide.to_string())

   country  year  nights_dom  nights_for  nights_tot
0  Albania  2018      931190     2143467     3074657
1  Albania  2019     1103905     2149514     3253419
2  Albania  2020      800028      805416     1605444
3  Albania  2021     1155185     2030887     3186072
4  Albania  2022     1339177     2492152     3831329
(376, 5)
country       0
year          0
nights_dom    0
nights_for    0
nights_tot    0
dtype: int64
             country  year  nights_dom  nights_for  nights_tot
0            Albania  2018      931190     2143467     3074657
1            Albania  2019     1103905     2149514     3253419
2            Albania  2020      800028      805416     1605444
3            Albania  2021     1155185     2030887     3186072
4            Albania  2022     1339177     2492152     3831329
5            Albania  2023     2101259     3906595     6007854
6            Albania  2024     2214777     5230937     7445714
7            Austria  2014    32341680    78099096   110440776
8            Austria  2015    33060945    80304956   113365901
9            Austria  2016    34558881    83398372   117957253
10           Austria  2017    35082222    86044321   121126543
11           Austria  2018    35935386    89293784   125229170
12           Austria  2019    36504339    91386215   127890554
13           Austria  2020    27990963    51142436    79133399
14           Austria  2021    26674565    40034274    66708839
15           Austria  2022    35592486    79470210   115062696
16           Austria  2023    36742409    91023501   127765910
17           Austria  2024    37192120    94009113   131201233
18           Austria  2025    37437110    97020394   134457504
19           Belgium  2014    15536809    17068872    32605681
20           Belgium  2015    19528328    18852087    38380415
21           Belgium  2016    19792020    17063194    36855214
22           Belgium  2017    20020465    18656843    38677308
23           Belgium  2018    20755601    20564683    41320284
24           Belgium  2019    21308009    21204838    42512847
25           Belgium  2020    13630700     6546786    20177486
26           Belgium  2021    21369885     7850962    29220847
27           Belgium  2022    23646343    19377781    43024124
28           Belgium  2023    23102177    21594425    44696602
29           Belgium  2024    22563809    22279289    44843098
30          Bulgaria  2014     7620593    14077798    21698391
31          Bulgaria  2015     8045535    13352281    21397816
32          Bulgaria  2016     9035330    16150666    25185996
33          Bulgaria  2017     8948529    17105567    26054096
34          Bulgaria  2018     9096088    17748925    26845013
35          Bulgaria  2019     9674945    17479846    27154791
36          Bulgaria  2020     7312194     4656289    11968483
37          Bulgaria  2021     9626501     7993767    17620268
38          Bulgaria  2022    11286336    12886955    24173291
39          Bulgaria  2023    12311004    14554042    26865046
40          Bulgaria  2024    12588156    15058045    27646201
41           Croatia  2014     5052330    61072661    66124991
42           Croatia  2015     5655990    65683010    71339000
43           Croatia  2016     5759532    72064582    77824114
44           Croatia  2017     5918043    80176804    86094847
45           Croatia  2018     6427780    83139873    89567653
46           Croatia  2019     7053932    84124151    91178083
47           Croatia  2020     5394858    35376486    40771344
48           Croatia  2021     7327520    62844164    70171684
49           Croatia  2022     7726655    82278728    90005383
50           Croatia  2023     8083165    84257983    92341148
51           Croatia  2024     8688362    84955334    93643696
52            Cyprus  2014      830943    12884399    13715342
53            Cyprus  2015      824517    12550320    13374837
54            Cyprus  2016      844182    14504702    15348884
55            Cyprus  2017      834104    15946809    16780913
56            Cyprus  2018      916840    16247342    17164182
57            Cyprus  2019     1012569    16561115    17573684
58            Cyprus  2020     1092094     2633160     3725254
59            Cyprus  2021     1547845     8193773     9741618
60            Cyprus  2022     1317451    12934983    14252434
61            Cyprus  2023     1207788    14428337    15636125
62            Cyprus  2024     1350625    16558853    17909478
63           Czechia  2014    20836817    22110112    42946929
64           Czechia  2015    23807391    23286515    47093906
65           Czechia  2016    25428808    24268149    49696957
66           Czechia  2017    26962382    26257013    53219395
67           Czechia  2018    28753901    26760021    55513922
68           Czechia  2019    29844204    27180563    57024767
69           Czechia  2020    23994436     7388058    31382494
70           Czechia  2021    25376927     6547315    31924242
71           Czechia  2022    32459645    18139667    50599312
72           Czechia  2023    32480862    23361609    55842471
73           Czechia  2024    31761973    25474111    57236084
74           Denmark  2014    19038780    10608119    29646899
75           Denmark  2015    19637924    11171416    30809340
76           Denmark  2016    20266251    11630004    31896255
77           Denmark  2017    20243007    11914787    32157794
78           Denmark  2018    20685784    12594611    33280395
79           Denmark  2019    21349055    12976570    34325625
80           Denmark  2020    18890042     4780488    23670530
81           Denmark  2021    22735819     5820235    28556054
82           Denmark  2022    25017892    13421956    38439848
83           Denmark  2023    24268566    14677540    38946106
84           Denmark  2024    24010206    15806432    39816638
85           Estonia  2014     1890165     3919299     5809464
86           Estonia  2015     2011663     3770207     5781870
87           Estonia  2016     2213547     4014581     6228128
88           Estonia  2017     2358880     4150419     6509299
89           Estonia  2018     2455763     4174552     6630315
90           Estonia  2019     2591410     4375637     6967047
91           Estonia  2020     2270210     1403802     3674012
92           Estonia  2021     2716254     1282743     3998997
93           Estonia  2022     3031814     2919059     5950873
94           Estonia  2023     3003818     3371044     6374862
95           Estonia  2024     2977933     3667975     6645908
96           Finland  2014    14075320     5710702    19786022
97           Finland  2015    14227773     5510350    19738123
98           Finland  2016    14572158     5771275    20343433
99           Finland  2017    15171320     6742834    21914154
100          Finland  2018    15392495     6842589    22235084
101          Finland  2019    16039663     7055997    23095660
102          Finland  2020    12032325     2291336    14323661
103          Finland  2021    15403349     2085366    17488715
104          Finland  2022    16996271     4974995    21971266
105          Finland  2023    17080229     5751832    22832061
106          Finland  2024    16309732     6368626    22678358
107           France  2014   271406467   130908700   402315167
108           France  2015   279587890   130464997   410052887
109           France  2016   280850016   123913410   404763426
110           France  2017   299558737   133499991   433058728
111           France  2018   302038667   140721383   442760050
112           France  2019   310563771   135990097   446553868
113           France  2020   212781655    45093660   257875315
114           France  2021   267865936    56523110   324389046
115           France  2022   324342680   125449581   449792261
116           France  2023   321903813   138367983   460271796
117           France  2024   317036065   140608197   457644262
118          Germany  2014   291722145    74805253   366527398
119          Germany  2015   299220311    78827773   378048084
120          Germany  2016   308904957    79946914   388851871
121          Germany  2017   318051999    83111219   401163218
122          Germany  2018   332594428    86961856   419556284
123          Germany  2019   347694001    89260847   436954848
124          Germany  2020   229025364    31732508   260757872
125          Germany  2021   235371154    30731500   266102654
126          Germany  2022   332792753    67616302   400409055
127          Germany  2023   351060606    80378429   431439035
128          Germany  2024   354827032    84792636   439619668
129           Greece  2014    20589198    80174274   100763472
130           Greece  2015    20900203    85164063   106064266
131           Greece  2016    22107192    87912850   110020042
132           Greece  2017    21974593    97034421   119009014
133           Greece  2018    24064088   118876323   142940411
134           Greece  2019    23623077   119971390   143594467
135           Greece  2020    12277230    26197786    38475016
136           Greece  2021    14963208    58923605    73886813
137           Greece  2022    21195814   111550090   132745904
138           Greece  2023    24103015   123106806   147209821
139           Greece  2024    24764341   128180321   152944662
140          Hungary  2014    13702543    12351330    26053873
141          Hungary  2015    14580503    12962395    27542898
142          Hungary  2016    15489123    13802045    29291168
143          Hungary  2017    16666938    14941781    31608719
144          Hungary  2018    17489671    15340449    32830120
145          Hungary  2019    17447388    15752573    33199961
146          Hungary  2020    10825115     3773567    14598682
147          Hungary  2021    12299937     5070834    17370771
148          Hungary  2022    17081903    12364137    29446040
149          Hungary  2023    16314547    14173761    30488308
150          Hungary  2024    16578557    15224253    31802810
151          Iceland  2014     1085049     4404834     5489883
152          Iceland  2015      930643     5605634     6536277
153          Iceland  2016     1044289     6764038     7808327
154          Iceland  2019     1089677     7316774     8406451
155          Iceland  2020     1467548     1828009     3295557
156          Iceland  2021     1939623     3072791     5012414
157          Iceland  2022     1968404     6578780     8547184
158          Iceland  2023     1961430     7557161     9518591
159          Ireland  2014    17889958    11276424    29166382
160          Ireland  2015    16247706    13462348    29710054
161          Ireland  2016    14915287    16190381    31105668
162          Ireland  2018    18257838    16813507    35071345
163          Ireland  2019    16295535    16285259    32580794
164          Ireland  2020    11624000     4516254    16140254
165          Ireland  2021     9696000     5234451    14930451
166          Ireland  2022    18456000    16474828    34930828
167          Ireland  2023    16274003    24362147    40636150
168          Ireland  2024    17327991    24349960    41677951
169            Italy  2014   190978299   186792507   377770806
170            Italy  2015   200249044   192625026   392874070
171            Italy  2016   203540299   199421814   402962113
172            Italy  2017   209970369   210658786   420629155
173            Italy  2018   212334391   216510546   428844937
174            Italy  2019   216076587   220662684   436739271
175            Italy  2020   143003478    65443607   208447085
176            Italy  2021   183054967   106123175   289178142
177            Italy  2022   210939098   201069434   412008532
178            Italy  2023   212987794   234182255   447170049
179            Italy  2024   212209602   253948443   466158045
180           Latvia  2014     1282484     2875934     4158418
181           Latvia  2015     1236025     2873885     4109910
182           Latvia  2016     1372065     3044532     4416597
183           Latvia  2017     1544402     3406527     4950929
184           Latvia  2018     1625773     3742966     5368739
185           Latvia  2019     1658379     3851303     5509682
186           Latvia  2020     1385037     1504305     2889342
187           Latvia  2021     1516390      863387     2379777
188           Latvia  2022     1769701     2113221     3882922
189           Latvia  2023     1793070     2577784     4370854
190           Latvia  2024     1850960     2841253     4692213
191    Liechtenstein  2014        2070      130202      132272
192    Liechtenstein  2015        2019      110465      112484
193    Liechtenstein  2016        3069      127747      130816
194    Liechtenstein  2017        3732      146892      150624
195    Liechtenstein  2018        3433      158728      162161
196    Liechtenstein  2019        3491      174095      177586
197    Liechtenstein  2020        3337      124166      127503
198    Liechtenstein  2021        6084      156302      162386
199    Liechtenstein  2022        3707      195032      198739
200    Liechtenstein  2023        4525      217741      222266
201    Liechtenstein  2024        5277      223302      228579
202        Lithuania  2014     3431178     3033826     6465004
203        Lithuania  2015     3570465     3010727     6581192
204        Lithuania  2016     3719254     3273420     6992674
205        Lithuania  2017     3933691     3431233     7364924
206        Lithuania  2018     4354797     3736850     8091647
207        Lithuania  2019     4804232     4142526     8946758
208        Lithuania  2020     3812166     1119591     4931757
209        Lithuania  2021     4359753     1182795     5542548
210        Lithuania  2022     5458686     2614444     8073130
211        Lithuania  2023     5471881     3001947     8473828
212        Lithuania  2024     5537953     3102171     8640124
213       Luxembourg  2014      354226     2513585     2867811
214       Luxembourg  2015      340447     2862290     3202737
215       Luxembourg  2016      332673     2936548     3269221
216       Luxembourg  2017      358649     2875330     3233979
217       Luxembourg  2018      371120     2802737     3173857
218       Luxembourg  2019      367594     2797162     3164756
219       Luxembourg  2020      403414     1289968     1693382
220       Luxembourg  2021      434995     1788781     2223776
221       Luxembourg  2022      488592     2807759     3296351
222       Luxembourg  2023      473681     3012273     3485954
223       Luxembourg  2024      458952     3225517     3684469
224            Malta  2014      352733     8428215     8780948
225            Malta  2015      373242     8542055     8915297
226            Malta  2016      348753     8622438     8971191
227            Malta  2017      396167     9184162     9580329
228            Malta  2018      429040     9685156    10114196
229            Malta  2019      474950     9436332     9911282
230            Malta  2020      547501     2397683     2945184
231            Malta  2021      672357     3940602     4612959
232            Malta  2022      661199     7549225     8210424
233            Malta  2023      685459     9206833     9892292
234            Malta  2024      715096    10605083    11320179
235       Montenegro  2015      747576    10307371    11054947
236       Montenegro  2016      721530    10528475    11250005
237       Montenegro  2017      431370     3459000     3890370
238       Montenegro  2022      528457     3787237     4315694
239       Montenegro  2023      564693     4560288     5124981
240       Montenegro  2024      597156     4603420     5200576
241      Netherlands  2014    65328010    34423552    99751562
242      Netherlands  2015    66236714    37297588   103534302
243      Netherlands  2016    66589317    39623541   106212858
244      Netherlands  2017    67528773    44169041   111697814
245      Netherlands  2018    69080031    47001546   116081577
246      Netherlands  2019    71692192    51750379   123442571
247      Netherlands  2020    64042422    21372439    85414861
248      Netherlands  2021    82479471    18614806   101094277
249      Netherlands  2022    84478125    48160140   132638265
250      Netherlands  2023    83168429    59104032   142272461
251      Netherlands  2024    83857504    61511827   145369331
252  North Macedonia  2014      618865      900148     1519013
253  North Macedonia  2015      619060     1020943     1640003
254  North Macedonia  2016      644167     1050917     1695084
255  North Macedonia  2017      686100     1289111     1975211
256  North Macedonia  2018      727607     1483982     2211589
257  North Macedonia  2019      721216     1573667     2294883
258  North Macedonia  2020      621922      252417      874339
259  North Macedonia  2021      652150      670134     1322284
260  North Macedonia  2022      675621     1143265     1818886
261  North Macedonia  2023      668340     1404586     2072926
262  North Macedonia  2024      650132     1530378     2180510
263           Norway  2014    22162724     8451333    30614057
264           Norway  2015    22739800     8851422    31591222
265           Norway  2016    23301585     9672993    32974578
266           Norway  2020    20402530     3318303    23720833
267           Norway  2021    23782515     3309531    27092046
268           Norway  2022    26313965     9813229    36127194
269           Norway  2023    25907064    11137428    37044492
270           Norway  2024    26162501    12425429    38587930
271           Poland  2014    53587348    12992241    66579589
272           Poland  2015    57476764    13757657    71234421
273           Poland  2016    63814635    15579225    79393860
274           Poland  2017    67175700    16705215    83880915
275           Poland  2018    71117812    17742651    88860463
276           Poland  2019    74659162    18683576    93342738
277           Poland  2020    44754216     6622952    51377168
278           Poland  2021    55672507     7165013    62837520
279           Poland  2022    75194553    14759246    89953799
280           Poland  2023    75786956    17010905    92797861
281           Poland  2024    79256114    18392029    97648143
282         Portugal  2014    19349092    35630345    54979437
283         Portugal  2015    20522609    38897329    59419938
284         Portugal  2016    22054931    43959295    66014226
285         Portugal  2017    23150944    48884842    72035786
286         Portugal  2018    24555272    49852324    74407596
287         Portugal  2019    26002000    51592254    77594254
288         Portugal  2020    16775906    13381894    30157800
289         Portugal  2021    22369511    20074908    42444419
290         Portugal  2022    27363326    49584659    76947985
291         Portugal  2023    27939627    56947203    84886830
292         Portugal  2024    28416210    59657373    88073583
293          Romania  2014    16467780     3762465    20230245
294          Romania  2015    18985269     4460017    23445286
295          Romania  2016    20462599     4812050    25274649
296          Romania  2017    21647603     5267970    26915573
297          Romania  2018    23154660     5306493    28461153
298          Romania  2019    24620841     5269053    29889894
299          Romania  2020    13458330      996134    14454464
300          Romania  2021    20508623     1913848    22422471
301          Romania  2022    22976069     3638152    26614221
302          Romania  2023    24738466     4467102    29205568
303          Romania  2024    25290103     4941101    30231204
304           Serbia  2014     3879642     2074680     5954322
305           Serbia  2015     4217374     2402065     6619439
306           Serbia  2016     4766970     2735528     7502498
307           Serbia  2020     4933011     1264383     6197394
308           Serbia  2021     5727351     2428804     8156155

In [766]:
tourism = arrivals_wide.merge(
nights_wide,
on=["country", "year"],
how="outer"
)

tourism

,country,year,arrivals_dom,arrivals_for,arrivals_tot,nights_dom,nights_for,nights_tot
0,Albania,2018,476294,766467,1242761,931190,2143467,3074657
1,Albania,2019,468787,784709,1253496,1103905,2149514,3253419
2,Albania,2020,371523,293657,665180,800028,805416,1605444
3,Albania,2021,545835,685081,1230916,1155185,2030887,3186072
4,Albania,2022,683467,886515,1569982,1339177,2492152,3831329
...,...,...,...,...,...,...,...,...
371,Türkiye,2023,37283173,40014918,77298091,72595189,130592641,203187830
372,Türkiye,2024,39198606,44044950,83243556,76418208,139599507,216017715
373,United Kingdom,2014,76849990,40849630,117699620,185710000,257670180,443380180
374,United Kingdom,2015,80136150,44274119,124410269,189788000,275650028,465438028
375,United Kingdom,2016,78571470,43469604,122041074,196903030,279453071,476356101

In [767]:
costs = pd.read_csv("../res/tin00196_linear.csv")

In [768]:
# Tieni solo le colonne utili
costs = costs[["geo", "TIME_PERIOD", "OBS_VALUE"]]

# Rinomina
costs = costs.rename(columns={
    "geo": "country",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "night_cost"
})

# Ordina
costs = costs.sort_values(
    by=["country", "year"]
).reset_index(drop=True)

In [769]:
costs = costs[
    costs["country"] != "European Union - 27 countries (from 2020)"
].reset_index(drop=True)

print(costs.to_string())
costs.dtypes

             country  year  night_cost
0            Albania  2017       20.04
1            Albania  2019       15.29
2            Albania  2020       32.14
3            Austria  2013      130.20
4            Austria  2014      127.19
5            Austria  2015      127.16
6            Austria  2016      130.55
7            Austria  2017      132.15
8            Austria  2018      134.50
9            Austria  2019      139.56
10           Austria  2020      117.81
11           Austria  2021      124.52
12           Austria  2022      147.42
13           Austria  2023      160.79
14           Austria  2024      175.14
15           Belgium  2013       96.13
16           Belgium  2014       84.61
17           Belgium  2015       83.43
18           Belgium  2016       89.80
19           Belgium  2017       87.47
20           Belgium  2018       81.83
21           Belgium  2019       89.43
22           Belgium  2020       59.12
23           Belgium  2021       63.74
24           Belgium  2022       89.00
25           Belgium  2023       96.71
26           Belgium  2024      102.15
27          Bulgaria  2013       28.54
28          Bulgaria  2014       35.23
29          Bulgaria  2015       36.29
30          Bulgaria  2016       36.52
31          Bulgaria  2017       36.78
32          Bulgaria  2018       37.12
33          Bulgaria  2019       42.74
34          Bulgaria  2020       45.34
35          Bulgaria  2021       50.05
36          Bulgaria  2022       69.08
37          Bulgaria  2023       68.84
38          Bulgaria  2024       82.57
39           Croatia  2013       42.71
40           Croatia  2014       39.11
41           Croatia  2015       46.35
42           Croatia  2016       45.71
43           Croatia  2017       49.94
44           Croatia  2018       56.53
45           Croatia  2019       52.09
46           Croatia  2020       36.49
47           Croatia  2021       43.02
48           Croatia  2022       56.53
49           Croatia  2023       67.46
50           Croatia  2024       83.49
51            Cyprus  2013       71.39
52            Cyprus  2014       70.16
53            Cyprus  2015       75.23
54            Cyprus  2016       82.89
55            Cyprus  2017       93.70
56            Cyprus  2018      107.03
57            Cyprus  2019      110.89
58            Cyprus  2020       70.09
59            Cyprus  2021       75.38
60            Cyprus  2022      120.12
61            Cyprus  2023      135.04
62            Cyprus  2024      131.60
63           Czechia  2013       30.31
64           Czechia  2014       26.58
65           Czechia  2015       31.54
66           Czechia  2016       31.90
67           Czechia  2017       34.16
68           Czechia  2018       38.52
69           Czechia  2019       37.67
70           Czechia  2020       25.92
71           Czechia  2021       31.61
72           Czechia  2022       46.28
73           Czechia  2023       56.45
74           Czechia  2024       55.97
75           Denmark  2013       94.54
76           Denmark  2014      105.24
77           Denmark  2015       91.84
78           Denmark  2016      119.55
79           Denmark  2017      161.88
80           Denmark  2018      172.07
81           Denmark  2019      120.18
82           Denmark  2020       80.08
83           Denmark  2021       81.47
84           Denmark  2022      101.23
85           Denmark  2023      105.67
86           Denmark  2024       85.33
87           Estonia  2013       55.95
88           Estonia  2014       60.79
89           Estonia  2015       60.31
90           Estonia  2016       67.92
91           Estonia  2017       73.20
92           Estonia  2018      102.60
93           Estonia  2019      110.13
94           Estonia  2020       87.48
95           Estonia  2021       91.20
96           Estonia  2022      128.16
97           Estonia  2023      133.25
98           Estonia  2024      133.13
99           Finland  2013      101.48
100          Finland  2014      101.25
101          Finland  2015      103.33
102          Finland  2016      101.56
103          Finland  2017      101.50
104          Finland  2018      108.71
105          Finland  2019       99.33
106          Finland  2020       59.00
107          Finland  2021       56.85
108          Finland  2022       90.25
109          Finland  2023      101.71
110          Finland  2024       98.50
111           France  2013       61.30
112           France  2014       63.11
113           France  2015       63.19
114           France  2016       65.05
115           France  2017       72.82
116           France  2018       76.14
117           France  2019       75.92
118           France  2020       64.62
119           France  2021       67.75
120           France  2022       83.74
121           France  2023       86.68
122           France  2024       91.12
123          Germany  2013       91.99
124          Germany  2014       85.67
125          Germany  2015       87.28
126          Germany  2016       88.30
127          Germany  2017       95.53
128          Germany  2018      111.34
129          Germany  2019      105.61
130          Germany  2020       78.29
131          Germany  2021       89.69
132          Germany  2022      116.21
133          Germany  2023      125.07
134          Germany  2024      129.48
135           Greece  2013       29.02
136           Greece  2014       28.51
137           Greece  2015       29.70
138           Greece  2016       32.03
139           Greece  2017       30.98
140           Greece  2018       33.74
141           Greece  2019       36.69
142           Greece  2020       29.36
143           Greece  2021       33.49
144           Greece  2022       44.92
145           Greece  2023       48.05
146           Greece  2024       49.41
147          Hungary  2013       33.08
148          Hungary  2014       36.71
149          Hungary  2015       38.55
150          Hungary  2016       41.19
151          Hungary  2017       44.86
152          Hungary  2018       43.39
153          Hungary  2019       42.14
154          Hungary  2020       37.82
155          Hungary  2021       40.91
156          Hungary  2022       52.22
157          Hungary  2023       70.44
158          Hungary  2024       73.79
159          Ireland  2013       96.49
160          Ireland  2014       99.42
161          Ireland  2015      106.38
162          Ireland  2016      108.16
163          Ireland  2017      112.16
164          Ireland  2018      112.71
165          Ireland  2019      116.52
166          Ireland  2020       97.22
167          Ireland  2021       96.14
168          Ireland  2022      124.37
169          Ireland  2023      142.96
170          Ireland  2024      138.01
171            Italy  2013       65.11
172            Italy  2014       57.02
173            Italy  2015       63.91
174            Italy  2016       68.06
175            Italy  2017       74.48
176            Italy  2018       73.15
177            Italy  2019       75.05
178            Italy  2020       61.62
179            Italy  2021       62.47
180            Italy  2022       71.77
181            Italy  2023       83.71
182            Italy  2024       85.66
183           Latvia  2013       39.70
184           Latvia  2014       34.66
185           Latvia  2015       42.31
186           Latvia  2016       36.71
187           Latvia  2017       47.01
188           Latvia  2018       50.14
189           Latvia  2019       59.48
190           Latvia  2020       35.65
191           Latvia  2021       45.22
192           Latvia  2022       63.62
193           Latvia  2023       73.49
194           Latvia  2024       77.08
195        Lithuania  2013       44.69
196        Lithuania  2014       48.32
197        Lithuania  2015       49.17
198        Lithuania  2016       52.84
199        Lithuania  2017       54.35
200        Lithuania  2018       55.84
201        Lithuania  2019       56.59
202        Lithuania  2020       51.28
203        Lithuania  2021       52.68
204        Lithuania  2022       63.26
205        Lithuania  2023       64.21
206        Lithuania  2024       62.84
207       Luxembourg  2013      119.21
208       Luxembourg  2014      130.31
209       Luxembourg  2015      122.37
210       Luxembourg  2016      120.33
211       Luxembourg  2017      112.05
212       Luxembourg  2018      131.70
213       Luxembourg  2019      154.01
214       Luxembourg  2020      107.14
215       Luxembourg  2021      114.93
216       Luxembourg  2022      175.21
217       Luxembourg  2023      182.83
218       Luxembourg  2024      190.60
219            Malta  2013      118.93
220            Malta  2014      112.49
221            Malta  2015      123.75
222            Malta  2016      113.78
223            Malta  2017      127.98
224            Malta  2018      134.10
225            Malta  2019      141.83
226            Malta  2020       90.01
227            Malta  2021      106.15
228            Malta  2022      123.14
229            Malta  2023      137.22
230            Malta  2024      135.09
231       Montenegro  2016       33.20
232       Montenegro  2017       38.21
233      Netherlands  2013       56.94
234      Netherlands  2014       57.28
235      Netherlands  2015       57.26
236      Netherlands  2016       59.50
237      Netherlands  2017       73.74
238      Netherlands  2018       74.07
239      Netherlands  2019       75.66
240      Netherlands  2020       48.78
241      Netherlands  2021       66.92
242      Netherlands  2022       79.23
243      Netherlands  2023       83.83
244      Netherlands  2024       95.84
245  North Macedonia  2019       34.92
246  North Macedonia  2020       30.15
247  North Macedonia  2021       38.32
248           Norway  2013      161.67
249           Norway  2014      147.96
250           Norway  2015      162.63
251           Norway  2016      161.38
252           Norway  2017      167.85
253           Norway  2018      143.95
254           Norway  2021       97.93
255           Norway  2022      165.95
256           Norway  2023      127.40
257           Norway  2024      148.56
258           Poland  2013       47.12
259           Poland  2014       32.42
260           Poland  2015       35.14
261           Poland  2016       35.46
262           Poland  2017       37.54
263           Poland  2018       39.93
264           Poland  2019       40.91
265           Poland  2020       36.36
266           Poland  2021       36.76
267           Poland  2022       44.33
268           Poland  2023       52.27
269           Poland  2024       60.15
270         Portugal  2013       22.10
271         Portugal  2014       35.20
272         Portugal  2015       39.05
273         Portugal  2016       36.90
274         Portugal  2017       38.54
275         Portugal  2018       43.39
276         Portugal  2019       49.72
277         Portugal  2020       37.50
278         Portugal  2021       42.20
279         Portugal  2022       56.70
280         Portugal  2023       61.37
281         Portugal  2024       69.27
282          Romania  2013       25.54
283          Romania  2014       26.15
284          Romania  2015       29.84
285          Romania  2016       32.19
286          Romania  2017       35.18
287          Romania  2018       38.25
288          Romania  2019       43.87
289          Romania  2020       41.15
290          Romania  2021       47.45
291          Romania  2022       67.16
292          Romania  2023       67.14
293          Romania  2024       75.18
294           Serbia  2018       41.74
295         Slovakia  2013       54.38
296         Slovakia  2014       58.03
297         Slovakia  2015       57.91
298         Slovakia  2016       55.34
299         Slovakia  2017       61.91
300         Slovakia  2018       58.24
301         Slovakia  2019       60.91
302         Slovakia  2020       48.27
303         Slovakia  2021       55.23
304         Slovakia  2022       71.90
305         Slovakia  2023       82.36
306         Slovakia  2024       95.82
307         Slovenia  2013       52.19
308         Slovenia  2014       55.78
309         Slovenia  2015       53.71
310         Slovenia  2016       53.95
311         Slovenia  2017       57.64
312         Slovenia  2018       61.24
313         Slovenia  2019       61.99
314         Slovenia  2020       39.17
315         Slovenia  2021       69.22
316         Slovenia  2022       75.11
317         Slovenia  2023       87.48
318         Slovenia  2024       92.90
319            Spain  2013       38.32
320            Spain  2014       39.12
321            Spain  2015       53.77
322            Spain  2016       57.95
323            Spain  2017       60.46
324            Spain  2018       64.72
325            Spain  2019       66.00
326            Spain  2020       45.57
327            Spain  2021       55.23
328            Spain  2022       71.74
329            Spain  2023       80.12
330            Spain  2024       83.75
331           Sweden  2014       59.91
332           Sweden  2015       65.25
333           Sweden  2016       55.47
334           Sweden  2017      155.97
335           Sweden  2018      146.96
336           Sweden  2019      140.16
337           Sweden  2020       74.61
338           Sweden  2021       83.53
339           Sweden  2022      112.89
340           Sweden  2024      149.78
341      Switzerland  2013      117.28
342      Switzerland  2014      105.89
343      Switzerland  2015      119.68
344      Switzerland  2016      120.67
345      Switzerland  2017      113.23
346      Switzerland  2018      115.08
347      Switzerland  2019      115.49
348      Switzerland  2020       89.71
349      Switzerland  2021      107.99
350      Switzerland  2022      130.65
351   United Kingdom  2013       69.25

country           str
year            int64
night_cost    float64
dtype: object

In [770]:
tourism = tourism.merge(
costs,
on=["country", "year"],
how="outer"
)

tourism

,country,year,arrivals_dom,arrivals_for,arrivals_tot,nights_dom,nights_for,nights_tot,night_cost
0,Albania,2017,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,20.04
1,Albania,2018,476294,766467,1242761,931190,2143467,3074657,NaN
2,Albania,2019,468787,784709,1253496,1103905,2149514,3253419,15.29
3,Albania,2020,371523,293657,665180,800028,805416,1605444,32.14
4,Albania,2021,545835,685081,1230916,1155185,2030887,3186072,NaN
...,...,...,...,...,...,...,...,...,...
409,Türkiye,2024,39198606,44044950,83243556,76418208,139599507,216017715,NaN
410,United Kingdom,2013,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,69.25
411,United Kingdom,2014,76849990,40849630,117699620,185710000,257670180,443380180,NaN
412,United Kingdom,2015,80136150,44274119,124410269,189788000,275650028,465438028,NaN
413,United Kingdom,2016,78571470,43469604,122041074,196903030,279453071,476356101,NaN

In [771]:
purpose = pd.read_csv("../res/tin00191_linear.csv")

In [772]:
# Tieni solo le colonne utili
purpose = purpose[["purpose", "geo", "TIME_PERIOD", "OBS_VALUE"]]

# Rinomina
purpose = purpose.rename(columns={
    "purpose": "purpose",
    "geo": "country",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "nights_purpose"
})

# Ordina
purpose = purpose.sort_values(
    by=["country", "year"]
).reset_index(drop=True)

purpose = purpose[
    purpose["country"] != "European Union - 27 countries (from 2020)"
].reset_index(drop=True)


print(purpose.to_string())
purpose.dtypes

                               purpose          country  year  nights_purpose
0                     Personal reasons          Albania  2017    2.203200e+07
1     Holidays, leisure and recreation          Albania  2017    6.682481e+06
2               Other personal reasons          Albania  2017    2.797408e+06
3      Visits to friends and relatives          Albania  2017    1.255211e+07
4               Professional, business          Albania  2017    4.583314e+06
5                                Total          Albania  2017    2.661531e+07
6                     Personal reasons          Albania  2019    2.655010e+07
7     Holidays, leisure and recreation          Albania  2019    1.074166e+07
8               Other personal reasons          Albania  2019    2.183308e+06
9      Visits to friends and relatives          Albania  2019    1.362513e+07
10              Professional, business          Albania  2019    2.727822e+06
11                               Total          Albania  2019    2.927792e+07
12                    Personal reasons          Albania  2020    1.421876e+07
13    Holidays, leisure and recreation          Albania  2020    8.852021e+06
14              Other personal reasons          Albania  2020    1.382769e+06
15     Visits to friends and relatives          Albania  2020    3.983969e+06
16              Professional, business          Albania  2020    4.258000e+05
17                               Total          Albania  2020    1.464456e+07
18                    Personal reasons          Austria  2013    9.253368e+07
19    Holidays, leisure and recreation          Austria  2013    6.893579e+07
20              Other personal reasons          Austria  2013    8.220980e+06
21     Visits to friends and relatives          Austria  2013    1.537691e+07
22              Professional, business          Austria  2013    1.256246e+07
23                               Total          Austria  2013    1.050961e+08
24                    Personal reasons          Austria  2014    9.368580e+07
25    Holidays, leisure and recreation          Austria  2014    7.312990e+07
26              Other personal reasons          Austria  2014    4.023568e+06
27     Visits to friends and relatives          Austria  2014    1.653234e+07
28              Professional, business          Austria  2014    1.366963e+07
29                               Total          Austria  2014    1.073554e+08
30                    Personal reasons          Austria  2015    9.238281e+07
31    Holidays, leisure and recreation          Austria  2015    7.299445e+07
32              Other personal reasons          Austria  2015    4.156869e+06
33     Visits to friends and relatives          Austria  2015    1.523150e+07
34              Professional, business          Austria  2015    1.342977e+07
35                               Total          Austria  2015    1.058126e+08
36                    Personal reasons          Austria  2016    9.962678e+07
37    Holidays, leisure and recreation          Austria  2016    7.565793e+07
38              Other personal reasons          Austria  2016    4.666996e+06
39     Visits to friends and relatives          Austria  2016    1.930185e+07
40              Professional, business          Austria  2016    1.187687e+07
41                               Total          Austria  2016    1.115036e+08
42                    Personal reasons          Austria  2017    1.007273e+08
43    Holidays, leisure and recreation          Austria  2017    7.814036e+07
44              Other personal reasons          Austria  2017    4.959813e+06
45     Visits to friends and relatives          Austria  2017    1.762718e+07
46              Professional, business          Austria  2017    1.132372e+07
47                               Total          Austria  2017    1.120511e+08
48                    Personal reasons          Austria  2018    9.893908e+07
49    Holidays, leisure and recreation          Austria  2018    7.148563e+07
50              Other personal reasons          Austria  2018    7.145755e+06
51     Visits to friends and relatives          Austria  2018    2.030770e+07
52              Professional, business          Austria  2018    9.757661e+06
53                               Total          Austria  2018    1.086967e+08
54                    Personal reasons          Austria  2019    1.034033e+08
55    Holidays, leisure and recreation          Austria  2019    7.551471e+07
56              Other personal reasons          Austria  2019    5.649761e+06
57     Visits to friends and relatives          Austria  2019    2.223879e+07
58              Professional, business          Austria  2019    1.177966e+07
59                               Total          Austria  2019    1.151829e+08
60                    Personal reasons          Austria  2020    5.469516e+07
61    Holidays, leisure and recreation          Austria  2020    3.486391e+07
62              Other personal reasons          Austria  2020    3.552614e+06
63     Visits to friends and relatives          Austria  2020    1.627864e+07
64              Professional, business          Austria  2020    7.149314e+06
65                               Total          Austria  2020    6.184448e+07
66                    Personal reasons          Austria  2021    7.683424e+07
67    Holidays, leisure and recreation          Austria  2021    4.922590e+07
68              Other personal reasons          Austria  2021    4.568954e+06
69     Visits to friends and relatives          Austria  2021    2.303938e+07
70              Professional, business          Austria  2021    7.820353e+06
71                               Total          Austria  2021    8.465459e+07
72                    Personal reasons          Austria  2022    1.212902e+08
73    Holidays, leisure and recreation          Austria  2022    8.202172e+07
74              Other personal reasons          Austria  2022    9.640170e+06
75     Visits to friends and relatives          Austria  2022    2.962828e+07
76              Professional, business          Austria  2022    1.332867e+07
77                               Total          Austria  2022    1.346188e+08
78                    Personal reasons          Austria  2023    1.367288e+08
79    Holidays, leisure and recreation          Austria  2023    8.755662e+07
80              Other personal reasons          Austria  2023    1.304997e+07
81     Visits to friends and relatives          Austria  2023    3.612217e+07
82              Professional, business          Austria  2023    1.389596e+07
83                               Total          Austria  2023    1.506247e+08
84                    Personal reasons          Austria  2024    1.411719e+08
85    Holidays, leisure and recreation          Austria  2024    9.633386e+07
86              Other personal reasons          Austria  2024    1.220771e+07
87     Visits to friends and relatives          Austria  2024    3.263034e+07
88              Professional, business          Austria  2024    1.474114e+07
89                               Total          Austria  2024    1.559130e+08
90                    Personal reasons          Belgium  2013    9.108037e+07
91    Holidays, leisure and recreation          Belgium  2013    7.687581e+07
92              Other personal reasons          Belgium  2013    1.956857e+06
93     Visits to friends and relatives          Belgium  2013    1.224770e+07
94              Professional, business          Belgium  2013    5.428686e+06
95                               Total          Belgium  2013    9.650905e+07
96                    Personal reasons          Belgium  2014    9.084492e+07
97    Holidays, leisure and recreation          Belgium  2014    7.567425e+07
98              Other personal reasons          Belgium  2014    2.681439e+06
99     Visits to friends and relatives          Belgium  2014    1.248922e+07
100             Professional, business          Belgium  2014    4.558717e+06
101                              Total          Belgium  2014    9.540363e+07
102                   Personal reasons          Belgium  2015    9.207594e+07
103   Holidays, leisure and recreation          Belgium  2015    7.771758e+07
104             Other personal reasons          Belgium  2015    1.900790e+06
105    Visits to friends and relatives          Belgium  2015    1.245757e+07
106             Professional, business          Belgium  2015    5.224671e+06
107                              Total          Belgium  2015    9.730061e+07
108                   Personal reasons          Belgium  2016    1.037695e+08
109   Holidays, leisure and recreation          Belgium  2016    8.822915e+07
110             Other personal reasons          Belgium  2016    1.799951e+06
111    Visits to friends and relatives          Belgium  2016    1.374042e+07
112             Professional, business          Belgium  2016    6.619282e+06
113                              Total          Belgium  2016    1.103888e+08
114                   Personal reasons          Belgium  2017    9.381931e+07
115   Holidays, leisure and recreation          Belgium  2017    7.578579e+07
116             Other personal reasons          Belgium  2017    1.698716e+06
117    Visits to friends and relatives          Belgium  2017    1.633480e+07
118             Professional, business          Belgium  2017    5.196200e+06
119                              Total          Belgium  2017    9.901551e+07
120                   Personal reasons          Belgium  2018    1.120681e+08
121   Holidays, leisure and recreation          Belgium  2018    9.133670e+07
122             Other personal reasons          Belgium  2018    1.496832e+06
123    Visits to friends and relatives          Belgium  2018    1.923460e+07
124             Professional, business          Belgium  2018    6.954332e+06
125                              Total          Belgium  2018    1.190225e+08
126                   Personal reasons          Belgium  2019    1.151164e+08
127   Holidays, leisure and recreation          Belgium  2019    9.000780e+07
128             Other personal reasons          Belgium  2019    4.789874e+06
129    Visits to friends and relatives          Belgium  2019    2.031874e+07
130             Professional, business          Belgium  2019    6.553923e+06
131                              Total          Belgium  2019    1.216703e+08
132                   Personal reasons          Belgium  2020    6.187186e+07
133   Holidays, leisure and recreation          Belgium  2020    4.552028e+07
134             Other personal reasons          Belgium  2020    3.397078e+06
135    Visits to friends and relatives          Belgium  2020    1.295451e+07
136             Professional, business          Belgium  2020    4.727843e+06
137                              Total          Belgium  2020    6.659971e+07
138                   Personal reasons          Belgium  2021    8.773988e+07
139   Holidays, leisure and recreation          Belgium  2021    6.546952e+07
140             Other personal reasons          Belgium  2021    4.276534e+06
141    Visits to friends and relatives          Belgium  2021    1.799382e+07
142             Professional, business          Belgium  2021    4.507784e+06
143                              Total          Belgium  2021    9.224766e+07
144                   Personal reasons          Belgium  2022    1.173225e+08
145   Holidays, leisure and recreation          Belgium  2022    9.064260e+07
146             Other personal reasons          Belgium  2022    4.442118e+06
147    Visits to friends and relatives          Belgium  2022    2.223778e+07
148             Professional, business          Belgium  2022    6.551956e+06
149                              Total          Belgium  2022    1.238744e+08
150                   Personal reasons          Belgium  2023    1.285748e+08
151   Holidays, leisure and recreation          Belgium  2023    9.806900e+07
152             Other personal reasons          Belgium  2023    5.047946e+06
153    Visits to friends and relatives          Belgium  2023    2.545782e+07
154             Professional, business          Belgium  2023    5.601058e+06
155                              Total          Belgium  2023    1.341758e+08
156                   Personal reasons          Belgium  2024    1.463757e+08
157   Holidays, leisure and recreation          Belgium  2024    1.120872e+08
158             Other personal reasons          Belgium  2024    5.380599e+06
159    Visits to friends and relatives          Belgium  2024    2.890794e+07
160             Professional, business          Belgium  2024    6.657284e+06
161                              Total          Belgium  2024    1.530330e+08
162                   Personal reasons         Bulgaria  2013    1.801207e+07
163   Holidays, leisure and recreation         Bulgaria  2013    1.084187e+07
164             Other personal reasons         Bulgaria  2013    1.155668e+06
165    Visits to friends and relatives         Bulgaria  2013    6.014528e+06
166             Professional, business         Bulgaria  2013    1.128975e+06
167                              Total         Bulgaria  2013    1.914104e+07
168                   Personal reasons         Bulgaria  2014    1.596341e+07
169   Holidays, leisure and recreation         Bulgaria  2014    9.289445e+06
170             Other personal reasons         Bulgaria  2014    1.374145e+06
171    Visits to friends and relatives         Bulgaria  2014    5.299820e+06
172             Professional, business         Bulgaria  2014    5.748430e+05
173                              Total         Bulgaria  2014    1.653825e+07
174                   Personal reasons         Bulgaria  2015    1.330064e+07
175   Holidays, leisure and recreation         Bulgaria  2015    8.024366e+06
176             Other personal reasons         Bulgaria  2015    8.562210e+05
177    Visits to friends and relatives         Bulgaria  2015    4.420050e+06
178             Professional, business         Bulgaria  2015    6.771640e+05
179                              Total         Bulgaria  2015    1.397780e+07
180                   Personal reasons         Bulgaria  2016    1.521707e+07
181   Holidays, leisure and recreation         Bulgaria  2016    9.443659e+06
182             Other personal reasons         Bulgaria  2016    8.197720e+05
183    Visits to friends and relatives         Bulgaria  2016    4.953636e+06
184             Professional, business         Bulgaria  2016    8.045680e+05
185                              Total         Bulgaria  2016    1.602164e+07
186                   Personal reasons         Bulgaria  2017    2.199017e+07
187   Holidays, leisure and recreation         Bulgaria  2017    1.352645e+07
188             Other personal reasons         Bulgaria  2017    1.029116e+06
189    Visits to friends and relatives         Bulgaria  2017    7.434606e+06
190             Professional, business         Bulgaria  2017    6.805920e+05
191                              Total         Bulgaria  2017    2.267076e+07
192                   Personal reasons         Bulgaria  2018    2.201540e+07
193   Holidays, leisure and recreation         Bulgaria  2018    1.314201e+07
194             Other personal reasons         Bulgaria  2018    8.886540e+05
195    Visits to friends and relatives         Bulgaria  2018    7.984730e+06
196             Professional, business         Bulgaria  2018    8.376790e+05
197                              Total         Bulgaria  2018    2.285308e+07
198                   Personal reasons         Bulgaria  2019    2.129337e+07
199   Holidays, leisure and recreation         Bulgaria  2019    1.281606e+07
200             Other personal reasons         Bulgaria  2019    1.211415e+06
201    Visits to friends and relatives         Bulgaria  2019    7.265898e+06
202             Professional, business         Bulgaria  2019    6.888880e+05
203                              Total         Bulgaria  2019    2.198226e+07
204                   Personal reasons         Bulgaria  2020    1.124198e+07
205   Holidays, leisure and recreation         Bulgaria  2020    7.391670e+06
206             Other personal reasons         Bulgaria  2020    3.769570e+05
207    Visits to friends and relatives         Bulgaria  2020    3.473355e+06
208             Professional, business         Bulgaria  2020    2.949960e+05
209                              Total         Bulgaria  2020    1.153698e+07
210                   Personal reasons         Bulgaria  2021    1.243798e+07
211   Holidays, leisure and recreation         Bulgaria  2021    8.825456e+06
212             Other personal reasons         Bulgaria  2021    5.533360e+05
213    Visits to friends and relatives         Bulgaria  2021    3.059188e+06
214             Professional, business         Bulgaria  2021    2.933120e+05
215                              Total         Bulgaria  2021    1.273129e+07
216                   Personal reasons         Bulgaria  2022    1.763916e+07
217   Holidays, leisure and recreation         Bulgaria  2022    1.253906e+07
218             Other personal reasons         Bulgaria  2022    9.070570e+05
219    Visits to friends and relatives         Bulgaria  2022    4.193040e+06
220             Professional, business         Bulgaria  2022    5.479170e+05
221                              Total         Bulgaria  2022    1.818707e+07
222                   Personal reasons         Bulgaria  2023    2.057955e+07
223   Holidays, leisure and recreation         Bulgaria  2023    1.378080e+07
224             Other personal reasons         Bulgaria  2023    1.246213e+06
225    Visits to friends and relatives         Bulgaria  2023    5.552540e+06
226             Professional, business         Bulgaria  2023    6.517620e+05
227                              Total         Bulgaria  2023    2.123132e+07
228                   Personal reasons         Bulgaria  2024    2.166843e+07
229   Holidays, leisure and recreation         Bulgaria  2024    1.555065e+07
230             Other personal reasons         Bulgaria  2024    1.133476e+06
231    Visits to friends and relatives         Bulgaria  2024    4.984304e+06
232             Professional, business         Bulgaria  2024    5.634630e+05
233                              Total         Bulgaria  2024    2.223189e+07
234                   Personal reasons          Croatia  2013    4.369685e+07
235   Holidays, leisure and recreation          Croatia  2013    1.951298e+07
236             Other personal reasons          Croatia  2013    7.515816e+06
237    Visits to friends and relatives          Croatia  2013    1.666806e+07
238             Professional, business          Croatia  2013    7.780895e+06
239                              Total          Croatia  2013    5.147774e+07
240                   Personal reasons          Croatia  2014    3.742236e+07
241   Holidays, leisure and recreation          Croatia  2014    1.955680e+07
242             Other personal reasons          Croatia  2014    6.055003e+06
243    Visits to friends and relatives          Croatia  2014    1.181055e+07
244             Professional, business          Croatia  2014    1.051796e+07
245                              Total          Croatia  2014    4.794032e+07
246                   Personal reasons          Croatia  2015    3.759296e+07
247   Holidays, leisure and recreation          Croatia  2015    1.999196e+07
248             Other personal reasons          Croatia  2015    4.548691e+06
249    Visits to friends and relatives          Croatia  2015    1.305231e+07
250             Professional, business          Croatia  2015    4.631386e+06
251                              Total          Croatia  2015    4.222434e+07
252                   Personal reasons          Croatia  2016    2.307795e+07
253   Holidays, leisure and recreation          Croatia  2016    1.442220e+07
254             Other personal reasons          Croatia  2016    2.589598e+06

purpose               str
country               str
year                int64
nights_purpose    float64
dtype: object

In [773]:
cols = ["nights_purpose"]
purpose[cols] = purpose[cols].astype("Int64")

print(purpose.to_string())
purpose.dtypes

                               purpose          country  year  nights_purpose
0                     Personal reasons          Albania  2017        22032000
1     Holidays, leisure and recreation          Albania  2017         6682481
2               Other personal reasons          Albania  2017         2797408
3      Visits to friends and relatives          Albania  2017        12552111
4               Professional, business          Albania  2017         4583314
5                                Total          Albania  2017        26615314
6                     Personal reasons          Albania  2019        26550098
7     Holidays, leisure and recreation          Albania  2019        10741657
8               Other personal reasons          Albania  2019         2183308
9      Visits to friends and relatives          Albania  2019        13625132
10              Professional, business          Albania  2019         2727822
11                               Total          Albania  2019        29277919
12                    Personal reasons          Albania  2020        14218759
13    Holidays, leisure and recreation          Albania  2020         8852021
14              Other personal reasons          Albania  2020         1382769
15     Visits to friends and relatives          Albania  2020         3983969
16              Professional, business          Albania  2020          425800
17                               Total          Albania  2020        14644559
18                    Personal reasons          Austria  2013        92533683
19    Holidays, leisure and recreation          Austria  2013        68935790
20              Other personal reasons          Austria  2013         8220980
21     Visits to friends and relatives          Austria  2013        15376914
22              Professional, business          Austria  2013        12562465
23                               Total          Austria  2013       105096149
24                    Personal reasons          Austria  2014        93685800
25    Holidays, leisure and recreation          Austria  2014        73129896
26              Other personal reasons          Austria  2014         4023568
27     Visits to friends and relatives          Austria  2014        16532336
28              Professional, business          Austria  2014        13669632
29                               Total          Austria  2014       107355432
30                    Personal reasons          Austria  2015        92382814
31    Holidays, leisure and recreation          Austria  2015        72994448
32              Other personal reasons          Austria  2015         4156869
33     Visits to friends and relatives          Austria  2015        15231496
34              Professional, business          Austria  2015        13429771
35                               Total          Austria  2015       105812584
36                    Personal reasons          Austria  2016        99626776
37    Holidays, leisure and recreation          Austria  2016        75657932
38              Other personal reasons          Austria  2016         4666996
39     Visits to friends and relatives          Austria  2016        19301848
40              Professional, business          Austria  2016        11876869
41                               Total          Austria  2016       111503645
42                    Personal reasons          Austria  2017       100727344
43    Holidays, leisure and recreation          Austria  2017        78140356
44              Other personal reasons          Austria  2017         4959813
45     Visits to friends and relatives          Austria  2017        17627175
46              Professional, business          Austria  2017        11323721
47                               Total          Austria  2017       112051065
48                    Personal reasons          Austria  2018        98939084
49    Holidays, leisure and recreation          Austria  2018        71485631
50              Other personal reasons          Austria  2018         7145755
51     Visits to friends and relatives          Austria  2018        20307698
52              Professional, business          Austria  2018         9757661
53                               Total          Austria  2018       108696746
54                    Personal reasons          Austria  2019       103403261
55    Holidays, leisure and recreation          Austria  2019        75514710
56              Other personal reasons          Austria  2019         5649761
57     Visits to friends and relatives          Austria  2019        22238791
58              Professional, business          Austria  2019        11779663
59                               Total          Austria  2019       115182924
60                    Personal reasons          Austria  2020        54695161
61    Holidays, leisure and recreation          Austria  2020        34863906
62              Other personal reasons          Austria  2020         3552614
63     Visits to friends and relatives          Austria  2020        16278641
64              Professional, business          Austria  2020         7149314
65                               Total          Austria  2020        61844475
66                    Personal reasons          Austria  2021        76834235
67    Holidays, leisure and recreation          Austria  2021        49225902
68              Other personal reasons          Austria  2021         4568954
69     Visits to friends and relatives          Austria  2021        23039379
70              Professional, business          Austria  2021         7820353
71                               Total          Austria  2021        84654588
72                    Personal reasons          Austria  2022       121290172
73    Holidays, leisure and recreation          Austria  2022        82021721
74              Other personal reasons          Austria  2022         9640170
75     Visits to friends and relatives          Austria  2022        29628281
76              Professional, business          Austria  2022        13328666
77                               Total          Austria  2022       134618838
78                    Personal reasons          Austria  2023       136728758
79    Holidays, leisure and recreation          Austria  2023        87556619
80              Other personal reasons          Austria  2023        13049973
81     Visits to friends and relatives          Austria  2023        36122166
82              Professional, business          Austria  2023        13895960
83                               Total          Austria  2023       150624718
84                    Personal reasons          Austria  2024       141171905
85    Holidays, leisure and recreation          Austria  2024        96333855
86              Other personal reasons          Austria  2024        12207711
87     Visits to friends and relatives          Austria  2024        32630339
88              Professional, business          Austria  2024        14741137
89                               Total          Austria  2024       155913042
90                    Personal reasons          Belgium  2013        91080366
91    Holidays, leisure and recreation          Belgium  2013        76875813
92              Other personal reasons          Belgium  2013         1956857
93     Visits to friends and relatives          Belgium  2013        12247696
94              Professional, business          Belgium  2013         5428686
95                               Total          Belgium  2013        96509052
96                    Personal reasons          Belgium  2014        90844916
97    Holidays, leisure and recreation          Belgium  2014        75674253
98              Other personal reasons          Belgium  2014         2681439
99     Visits to friends and relatives          Belgium  2014        12489223
100             Professional, business          Belgium  2014         4558717
101                              Total          Belgium  2014        95403633
102                   Personal reasons          Belgium  2015        92075939
103   Holidays, leisure and recreation          Belgium  2015        77717579
104             Other personal reasons          Belgium  2015         1900790
105    Visits to friends and relatives          Belgium  2015        12457569
106             Professional, business          Belgium  2015         5224671
107                              Total          Belgium  2015        97300609
108                   Personal reasons          Belgium  2016       103769522
109   Holidays, leisure and recreation          Belgium  2016        88229152
110             Other personal reasons          Belgium  2016         1799951
111    Visits to friends and relatives          Belgium  2016        13740419
112             Professional, business          Belgium  2016         6619282
113                              Total          Belgium  2016       110388803
114                   Personal reasons          Belgium  2017        93819309
115   Holidays, leisure and recreation          Belgium  2017        75785789
116             Other personal reasons          Belgium  2017         1698716
117    Visits to friends and relatives          Belgium  2017        16334803
118             Professional, business          Belgium  2017         5196200
119                              Total          Belgium  2017        99015509
120                   Personal reasons          Belgium  2018       112068134
121   Holidays, leisure and recreation          Belgium  2018        91336698
122             Other personal reasons          Belgium  2018         1496832
123    Visits to friends and relatives          Belgium  2018        19234604
124             Professional, business          Belgium  2018         6954332
125                              Total          Belgium  2018       119022466
126                   Personal reasons          Belgium  2019       115116412
127   Holidays, leisure and recreation          Belgium  2019        90007799
128             Other personal reasons          Belgium  2019         4789874
129    Visits to friends and relatives          Belgium  2019        20318738
130             Professional, business          Belgium  2019         6553923
131                              Total          Belgium  2019       121670335
132                   Personal reasons          Belgium  2020        61871865
133   Holidays, leisure and recreation          Belgium  2020        45520280
134             Other personal reasons          Belgium  2020         3397078
135    Visits to friends and relatives          Belgium  2020        12954507
136             Professional, business          Belgium  2020         4727843
137                              Total          Belgium  2020        66599708
138                   Personal reasons          Belgium  2021        87739875
139   Holidays, leisure and recreation          Belgium  2021        65469519
140             Other personal reasons          Belgium  2021         4276534
141    Visits to friends and relatives          Belgium  2021        17993823
142             Professional, business          Belgium  2021         4507784
143                              Total          Belgium  2021        92247659
144                   Personal reasons          Belgium  2022       117322491
145   Holidays, leisure and recreation          Belgium  2022        90642596
146             Other personal reasons          Belgium  2022         4442118
147    Visits to friends and relatives          Belgium  2022        22237777
148             Professional, business          Belgium  2022         6551956
149                              Total          Belgium  2022       123874447
150                   Personal reasons          Belgium  2023       128574758
151   Holidays, leisure and recreation          Belgium  2023        98068995
152             Other personal reasons          Belgium  2023         5047946
153    Visits to friends and relatives          Belgium  2023        25457817
154             Professional, business          Belgium  2023         5601058
155                              Total          Belgium  2023       134175816
156                   Personal reasons          Belgium  2024       146375707
157   Holidays, leisure and recreation          Belgium  2024       112087166
158             Other personal reasons          Belgium  2024         5380599
159    Visits to friends and relatives          Belgium  2024        28907942
160             Professional, business          Belgium  2024         6657284
161                              Total          Belgium  2024       153032991
162                   Personal reasons         Bulgaria  2013        18012068
163   Holidays, leisure and recreation         Bulgaria  2013        10841873
164             Other personal reasons         Bulgaria  2013         1155668
165    Visits to friends and relatives         Bulgaria  2013         6014528
166             Professional, business         Bulgaria  2013         1128975
167                              Total         Bulgaria  2013        19141043
168                   Personal reasons         Bulgaria  2014        15963409
169   Holidays, leisure and recreation         Bulgaria  2014         9289445
170             Other personal reasons         Bulgaria  2014         1374145
171    Visits to friends and relatives         Bulgaria  2014         5299820
172             Professional, business         Bulgaria  2014          574843
173                              Total         Bulgaria  2014        16538253
174                   Personal reasons         Bulgaria  2015        13300637
175   Holidays, leisure and recreation         Bulgaria  2015         8024366
176             Other personal reasons         Bulgaria  2015          856221
177    Visits to friends and relatives         Bulgaria  2015         4420050
178             Professional, business         Bulgaria  2015          677164
179                              Total         Bulgaria  2015        13977801
180                   Personal reasons         Bulgaria  2016        15217066
181   Holidays, leisure and recreation         Bulgaria  2016         9443659
182             Other personal reasons         Bulgaria  2016          819772
183    Visits to friends and relatives         Bulgaria  2016         4953636
184             Professional, business         Bulgaria  2016          804568
185                              Total         Bulgaria  2016        16021635
186                   Personal reasons         Bulgaria  2017        21990173
187   Holidays, leisure and recreation         Bulgaria  2017        13526452
188             Other personal reasons         Bulgaria  2017         1029116
189    Visits to friends and relatives         Bulgaria  2017         7434606
190             Professional, business         Bulgaria  2017          680592
191                              Total         Bulgaria  2017        22670765
192                   Personal reasons         Bulgaria  2018        22015397
193   Holidays, leisure and recreation         Bulgaria  2018        13142012
194             Other personal reasons         Bulgaria  2018          888654
195    Visits to friends and relatives         Bulgaria  2018         7984730
196             Professional, business         Bulgaria  2018          837679
197                              Total         Bulgaria  2018        22853076
198                   Personal reasons         Bulgaria  2019        21293370
199   Holidays, leisure and recreation         Bulgaria  2019        12816057
200             Other personal reasons         Bulgaria  2019         1211415
201    Visits to friends and relatives         Bulgaria  2019         7265898
202             Professional, business         Bulgaria  2019          688888
203                              Total         Bulgaria  2019        21982258
204                   Personal reasons         Bulgaria  2020        11241983
205   Holidays, leisure and recreation         Bulgaria  2020         7391670
206             Other personal reasons         Bulgaria  2020          376957
207    Visits to friends and relatives         Bulgaria  2020         3473355
208             Professional, business         Bulgaria  2020          294996
209                              Total         Bulgaria  2020        11536979
210                   Personal reasons         Bulgaria  2021        12437981
211   Holidays, leisure and recreation         Bulgaria  2021         8825456
212             Other personal reasons         Bulgaria  2021          553336
213    Visits to friends and relatives         Bulgaria  2021         3059188
214             Professional, business         Bulgaria  2021          293312
215                              Total         Bulgaria  2021        12731292
216                   Personal reasons         Bulgaria  2022        17639156
217   Holidays, leisure and recreation         Bulgaria  2022        12539060
218             Other personal reasons         Bulgaria  2022          907057
219    Visits to friends and relatives         Bulgaria  2022         4193040
220             Professional, business         Bulgaria  2022          547917
221                              Total         Bulgaria  2022        18187073
222                   Personal reasons         Bulgaria  2023        20579554
223   Holidays, leisure and recreation         Bulgaria  2023        13780801
224             Other personal reasons         Bulgaria  2023         1246213
225    Visits to friends and relatives         Bulgaria  2023         5552540
226             Professional, business         Bulgaria  2023          651762
227                              Total         Bulgaria  2023        21231317
228                   Personal reasons         Bulgaria  2024        21668429
229   Holidays, leisure and recreation         Bulgaria  2024        15550649
230             Other personal reasons         Bulgaria  2024         1133476
231    Visits to friends and relatives         Bulgaria  2024         4984304
232             Professional, business         Bulgaria  2024          563463
233                              Total         Bulgaria  2024        22231891
234                   Personal reasons          Croatia  2013        43696848
235   Holidays, leisure and recreation          Croatia  2013        19512975
236             Other personal reasons          Croatia  2013         7515816
237    Visits to friends and relatives          Croatia  2013        16668057
238             Professional, business          Croatia  2013         7780895
239                              Total          Croatia  2013        51477742
240                   Personal reasons          Croatia  2014        37422357
241   Holidays, leisure and recreation          Croatia  2014        19556801
242             Other personal reasons          Croatia  2014         6055003
243    Visits to friends and relatives          Croatia  2014        11810553
244             Professional, business          Croatia  2014        10517963
245                              Total          Croatia  2014        47940320
246                   Personal reasons          Croatia  2015        37592955
247   Holidays, leisure and recreation          Croatia  2015        19991955
248             Other personal reasons          Croatia  2015         4548691
249    Visits to friends and relatives          Croatia  2015        13052309
250             Professional, business          Croatia  2015         4631386
251                              Total          Croatia  2015        42224340
252                   Personal reasons          Croatia  2016        23077948
253   Holidays, leisure and recreation          Croatia  2016        14422203
254             Other personal reasons          Croatia  2016         2589598

purpose             str
country             str
year              int64
nights_purpose    Int64
dtype: object

In [774]:
purpose_wide = purpose.pivot_table(
    index=["country", "year"],
    columns="purpose",
    values="nights_purpose",
    aggfunc="sum"
).reset_index()


purpose_wide = purpose_wide.rename(columns={
    "Holidays, leisure and recreation": "purpose_leisure",
    "Professional, business": "purpose_work",
    "Visits to friends and relatives": "purpose_visit",
    "Personal reasons": "purpose_personal",
    "Other personal reasons": "purpose_other",
    "Total": "purpose_tot"
})

purpose_wide = purpose_wide[[
    "country",
    "year",
    "purpose_leisure",
    "purpose_work",
    "purpose_visit",
    "purpose_personal",
    "purpose_other",
    "purpose_tot"
]]

print(purpose_wide.to_string())

purpose          country  year  purpose_leisure  purpose_work  purpose_visit  purpose_personal  purpose_other  purpose_tot
0                Albania  2017          6682481       4583314       12552111          22032000        2797408     26615314
1                Albania  2019         10741657       2727822       13625132          26550098        2183308     29277919
2                Albania  2020          8852021        425800        3983969          14218759        1382769     14644559
3                Austria  2013         68935790      12562465       15376914          92533683        8220980    105096149
4                Austria  2014         73129896      13669632       16532336          93685800        4023568    107355432
5                Austria  2015         72994448      13429771       15231496          92382814        4156869    105812584
6                Austria  2016         75657932      11876869       19301848          99626776        4666996    111503645
7                Austria  2017         78140356      11323721       17627175         100727344        4959813    112051065
8                Austria  2018         71485631       9757661       20307698          98939084        7145755    108696746
9                Austria  2019         75514710      11779663       22238791         103403261        5649761    115182924
10               Austria  2020         34863906       7149314       16278641          54695161        3552614     61844475
11               Austria  2021         49225902       7820353       23039379          76834235        4568954     84654588
12               Austria  2022         82021721      13328666       29628281         121290172        9640170    134618838
13               Austria  2023         87556619      13895960       36122166         136728758       13049973    150624718
14               Austria  2024         96333855      14741137       32630339         141171905       12207711    155913042
15               Belgium  2013         76875813       5428686       12247696          91080366        1956857     96509052
16               Belgium  2014         75674253       4558717       12489223          90844916        2681439     95403633
17               Belgium  2015         77717579       5224671       12457569          92075939        1900790     97300609
18               Belgium  2016         88229152       6619282       13740419         103769522        1799951    110388803
19               Belgium  2017         75785789       5196200       16334803          93819309        1698716     99015509
20               Belgium  2018         91336698       6954332       19234604         112068134        1496832    119022466
21               Belgium  2019         90007799       6553923       20318738         115116412        4789874    121670335
22               Belgium  2020         45520280       4727843       12954507          61871865        3397078     66599708
23               Belgium  2021         65469519       4507784       17993823          87739875        4276534     92247659
24               Belgium  2022         90642596       6551956       22237777         117322491        4442118    123874447
25               Belgium  2023         98068995       5601058       25457817         128574758        5047946    134175816
26               Belgium  2024        112087166       6657284       28907942         146375707        5380599    153032991
27              Bulgaria  2013         10841873       1128975        6014528          18012068        1155668     19141043
28              Bulgaria  2014          9289445        574843        5299820          15963409        1374145     16538253
29              Bulgaria  2015          8024366        677164        4420050          13300637         856221     13977801
30              Bulgaria  2016          9443659        804568        4953636          15217066         819772     16021635
31              Bulgaria  2017         13526452        680592        7434606          21990173        1029116     22670765
32              Bulgaria  2018         13142012        837679        7984730          22015397         888654     22853076
33              Bulgaria  2019         12816057        688888        7265898          21293370        1211415     21982258
34              Bulgaria  2020          7391670        294996        3473355          11241983         376957     11536979
35              Bulgaria  2021          8825456        293312        3059188          12437981         553336     12731292
36              Bulgaria  2022         12539060        547917        4193040          17639156         907057     18187073
37              Bulgaria  2023         13780801        651762        5552540          20579554        1246213     21231317
38              Bulgaria  2024         15550649        563463        4984304          21668429        1133476     22231891
39               Croatia  2013         19512975       7780895       16668057          43696848        7515816     51477742
40               Croatia  2014         19556801      10517963       11810553          37422357        6055003     47940320
41               Croatia  2015         19991955       4631386       13052309          37592955        4548691     42224340
42               Croatia  2016         14422203       3703319        6066147          23077948        2589598     26781267
43               Croatia  2017         16554671       4804039        7473254          26633172        2605247     31437211
44               Croatia  2018         15152540       4468153        7377986          24738769        2208243     29206922
45               Croatia  2019         17155924       3646832        8468650          28229007        2604434     31875839
46               Croatia  2020         11948801        881775        5441139          18566235        1176295     19448010
47               Croatia  2021         15101747       1907831        6291276          22994782        1601759     24902613
48               Croatia  2022         17148822       1991626        6396395          24585276        1040059     26576902
49               Croatia  2023         18858690       2949894        8783582          29478476        1836203     32428371
50               Croatia  2024         20799478       1980348        8173978          30069015        1095559     32049363
51                Cyprus  2013          8477596       1207047        4208885          15792375        3105894     16999423
52                Cyprus  2014          8414587       1732916        5245571          17340400        3680242     19073316
53                Cyprus  2015          6261123       1426221        5577550          14730847        2892175     16157068
54                Cyprus  2016          7197125       1237935        5174181          15837339        3466032     17075275
55                Cyprus  2017          8906777       1517937        4219006          16401111        3275327     17919048
56                Cyprus  2018          9121593       1105383        2923974          14534395        2488828     15639778
57                Cyprus  2019          8974660       1334491        4091053          15976501        2910788     17310993
58                Cyprus  2020          5364174        382755        1486613          10064041        3213254     10446796
59                Cyprus  2021          6520130        537435        1582340           9415909        1313439      9953344
60                Cyprus  2022          7563536        816891        3831375          13010663        1615752     13827553
61                Cyprus  2023          9939940       1203914        3880571          15332686        1512175     16536600
62                Cyprus  2024         11209685       1052678        4427349          16964238        1327203     18016916
63               Czechia  2013         88490674       4349460       33462207         126664599        4711719    131014059
64               Czechia  2014         89223278       3441769       38380400         132228650        4624972    135670419
65               Czechia  2015         79849422       3330221       35857004         120787429        5081003    124117650
66               Czechia  2016         93399920       3351779       36296454         134383118        4686744    137734897
67               Czechia  2017         97239625       3736370       39085893         142717744        6392226    146454114
68               Czechia  2018         96455411       3719355       35245445         136921820        5220964    140641174
69               Czechia  2019        101545247       4065248       36009097         143687775        6133431    147753024
70               Czechia  2020         73887890       1292739       23798370          99408993        1722733    100701732
71               Czechia  2021         81619906       1832800       28282795         112385198        2482497    114217998
72               Czechia  2022         96680126       2430469       32836136         134127499        4611238    136557968
73               Czechia  2023         89899245       2344955       27366705         123408851        6142901    125753806
74               Czechia  2024         91583410       2743115       27610332         123834251        4640509    126577366
75               Denmark  2013         60381458       9796102       37157156          98075654         537040    107871756
76               Denmark  2014         64349702       6554012       41805262         106478056         323092    113032069
77               Denmark  2015         70676367      10511935       39651030         110779582         452185    121291517
78               Denmark  2016         58243055       6779392       36920518          95640809         477237    102420201
79               Denmark  2017         60675119      10411711       26236800          90861538        3949619    101273248
80               Denmark  2018         55232250      10645935       18751153          76891586        2908183     87537521
81               Denmark  2019         88741899      13012494       30171419         123451207        4537889    136463701
82               Denmark  2020         57812135       1037706       21371757          82498418        3314525     83536123
83               Denmark  2021         41498867       5406681       16909199          59719291        1311225     65125972
84               Denmark  2022         51692446       7456531       19442702          74009596        2874448     81466127
85               Denmark  2023         55835139       9438608       16101995          74747121        2809986     84185728
86               Denmark  2024         85684990       6836079       24821008         115275638        4769639    122111716
87               Estonia  2013          5579039       2113315        3952425           9611925          80461     11725240
88               Estonia  2014          6115054       2552139        5133343          11539242         290845     14091381
89               Estonia  2015          6752314       3336946        4468802          12191358         970241     15528304
90               Estonia  2016          6576799       3000211        4978361          11833516         278355     14833727
91               Estonia  2017          7700386       2649953        4094445          12451028         656196     15100980
92               Estonia  2018         11710447       2634396        5693161          17920941         517333     20555336
93               Estonia  2019          9160650       2610768        4311477          14434904         962777     17045673
94               Estonia  2020          4765038       2074120        1999573           7104137         339526      9178257
95               Estonia  2021          5401229       1768677        2368942           8073027         302857      9841705
96               Estonia  2022          7665566       1519187        2933650          10999959         400743     12519146
97               Estonia  2023          9333355       2911862        3895784          13720364         491225     16632226
98               Estonia  2024         10137549       2384204        4547274          15246978         562155     17631181
99               Finland  2013         68442629      13614228       41824051         118722790        8456110    132337018
100              Finland  2014         65080262      15293714       42007545         114010096        6922290    129303810
101              Finland  2015         66707422      13360818       42488666         114908310        5712222    128269128
102              Finland  2016         65040037      16557688       44964323         115692701        5688341    132250389
103              Finland  2017         71288033      15323824       41870603         120564281        7405645    135888105
104              Finland  2018         73616085      14613070       39440619         119253074        6196371    133866145
105              Finland  2019         77675806      18616034       41879893         128498619        8942919    147114653
106              Finland  2020         65941492      10031292       29894102         108016551       12180956    118047843
107              Finland  2021         62053465       7001303       40747869         113192087       10390754    120193391
108              Finland  2022         79932236      12299138       38535874         128119583        9651473    140418721
109              Finland  2023         74465690      12568255       36069320         123481941       12946932    136050197
110              Finland  2024         77861571      10743354       38361095         132066267       15843601    142809621
111               France  2013        666293318      74381061      432894258        1177899648       78712072   1252280709
112               France  2014        678369098      71201764      428107434        1189953735       83477204   1261155500
113               France  2015        601905317      53424732      390874018        1060518125       67738790   1113942857
114               France  2016        594583629      54126888      379218236        1039998283       66196418   1094125171
115               France  2017        626789641      78461800      344206272        1049371921       78376007   1127833720
116               France  2018        660029894      74835987      321920271        1063781398       81831233   1138617385
117               France  2019        635182175      71103880      312151695        1021743733       74409864   1092847613
118               France  2020        463623018      48770041      262155105         800314794       74536671    849084834
119               France  2021        518116329      52542599      305637304         908435331       84681698    960977930
120               France  2022        608715246      64487207      320254705        1015244700       86274748   1079731907
121               France  2023        661876535      59727219      335447333        1063907617       66583749   1123634836
122               France  2024        636588547      88205993      336720487        1029451910       56142876   1117657902
123              Germany  2013        796094427     134968368      318267743        1178024126       63661955   1312992493
124              Germany  2014        807739235     142172582      295207734        1157965754       55018785   1300138336
125              Germany  2015        799564001     124859051      333118581        1186949304       54266722   1311808356
126              Germany  2016        831869978     145352285      324481907        1214745591       58393705   1360097876
127              Germany  2017        845297449     141142904      291993749        1208220120       70928923   1349363024
128              Germany  2018        994724765     136987367      288681067        1361559780       78153948   1498547146
129              Germany  2019        935408019     139323601      306660089        1314315249       72247141   1453638850
130              Germany  2020        431030843      58918675      259204329         718721537       28486365    777640211
131              Germany  2021        562978406     101850320      264152102         854964505       27833997    956814825
132              Germany  2022        930436526     108032049      241920075        1209420961       37064360   1317453011
133              Germany  2023        925642420     110656293      316069003        1302767072       61055649   1413423364
134              Germany  2024       1066461937     117420115      325050670        1443193342       51680735   1560613457
135               Greece  2013         39079284       3218043       14369277          55563413        2114852     58781457
136               Greece  2014         43611092       3729817       12973433          60247379        3662854     63977197
137               Greece  2015         41987316       2463743       10979978          54975525        2008231     57439268
138               Greece  2016         39953907       3292216       10748466          53046915        2344542     56339130
139               Greece  2017         46196130       2145392       10668725          59368259        2503404     61513651
140               Greece  2018         52762062       1435682       11603432          66565271        2199777     68000953
141               Greece  2019         46418216       2137387       13280834          61288888        1589838     63426276
142               Greece  2020         46704511        863049        7229019          56041259        2107729     56904308
143               Greece  2021         50346172       1001747        6702989          59021976        1972816     60023723
144               Greece  2022         52385785       1373798       12483523          67219935        2350627     68593733
145               Greece  2023         52679693        964826       10587852          64993656        1726110     65958482
146               Greece  2024         57328930        977465        9378679          68252758        1545149     69230223
147              Hungary  2013         32809815       2136711       24433755          59222069        1978499     61358780
148              Hungary  2014         34533233       2180064       25595830          63152596        3023533     65332660
149              Hungary  2015         35118347       2334534       27188585          63939104        1632172     66273638
150              Hungary  2016         37171744       2350230       24686235          64088907        2230928     66439137
151              Hungary  2017         41678866       2145790       21216719          64753994        1858409     66899784
152              Hungary  2018         43701311       1680010       23601959          68914342        1611072     70594352
153              Hungary  2019         48213918       2298091       23518712          75071447        3338817     77369538
154              Hungary  2020         23656627       1260345       11579551          36181336         945158     37441681
155              Hungary  2021         26231204       1723627       12791727          39955559         932628     41679186
156              Hungary  2022         37409696       2571190       17766111          56431031        1255224     59002221
157              Hungary  2023         44612991       2992592       16336539          63572238        2622708     66564830
158              Hungary  2024         47300873       3437874       14862617          64204582        2041092     67642456
159              Ireland  2013         35377310       2942387       14876122          57715540        7462107     60657926
160              Ireland  2014         36144167       3699610       15082714          58545733        7318851     62245343

In [775]:
tourism = tourism.merge(
purpose_wide,
on=["country", "year"],
how="outer"
)

tourism

,country,year,arrivals_dom,arrivals_for,arrivals_tot,nights_dom,nights_for,nights_tot,night_cost,purpose_leisure,purpose_work,purpose_visit,purpose_personal,purpose_other,purpose_tot
0,Albania,2017,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,20.04,6682481,4583314,12552111,22032000,2797408,26615314
1,Albania,2018,476294,766467,1242761,931190,2143467,3074657,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,Albania,2019,468787,784709,1253496,1103905,2149514,3253419,15.29,10741657,2727822,13625132,26550098,2183308,29277919
3,Albania,2020,371523,293657,665180,800028,805416,1605444,32.14,8852021,425800,3983969,14218759,1382769,14644559
4,Albania,2021,545835,685081,1230916,1155185,2030887,3186072,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,Türkiye,2024,39198606,44044950,83243556,76418208,139599507,216017715,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
410,United Kingdom,2013,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,69.25,492599248,79569396,285183009,804313588,26531332,883882984
411,United Kingdom,2014,76849990,40849630,117699620,185710000,257670180,443380180,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
412,United Kingdom,2015,80136150,44274119,124410269,189788000,275650028,465438028,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
413,United Kingdom,2016,78571470,43469604,122041074,196903030,279453071,476356101,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [777]:
tourism.to_csv('../res/report_tourism.csv', sep=',', encoding='utf-8')